plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 40

Metrics/ClassLength:
  Max: 400

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 20

RSpec/SpecFilePathFormat:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultipleComparison:
  Enabled: false


