# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

# lexer_kit is needed for the :ruby backend (lexer/dsl.rb).
# Removed from gemspec runtime dependency since :ffi backend doesn't need it.
# For monorepo development, prefer the local checkout.
if File.directory?(File.expand_path('../../lexer_kit', __dir__))
  gem 'lexer_kit', path: '../../lexer_kit'
else
  gem 'lexer_kit', '~> 0.5'
end

group :development, :test do
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-rspec', '~> 2.22'
  gem 'simplecov', '~> 0.22', require: false
end
