# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

# LexerKit for fast lexical analysis
gem 'lexer_kit', path: '../../lexer_kit'

group :development, :test do
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-rspec', '~> 2.22'
  gem 'simplecov', '~> 0.22', require: false
end
