# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'lexer_kit', '~> 0.5'

group :development, :test do
  gem 'rake'
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'simplecov', require: false
end
