#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 168
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 12
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  aux_sym__text_char_token1 = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACK = 3,
  anon_sym_QMARK = 4,
  anon_sym_BANG = 5,
  anon_sym_POUND = 6,
  anon_sym_if = 7,
  anon_sym_SLASH = 8,
  anon_sym_else = 9,
  anon_sym_unless = 10,
  anon_sym_each = 11,
  anon_sym_as = 12,
  anon_sym_unsecure = 13,
  anon_sym_include = 14,
  anon_sym_EQ = 15,
  sym_delimiter_escape = 16,
  sym_tag_open = 17,
  sym_tag_close = 18,
  anon_sym_DOT = 19,
  sym_identifier = 20,
  sym_include_name = 21,
  sym_comment = 22,
  sym__ws = 23,
  sym_template = 24,
  sym__node = 25,
  sym_text = 26,
  sym__text_char = 27,
  sym_variable = 28,
  sym_modifier = 29,
  sym_if_block = 30,
  sym_if_open = 31,
  sym_if_close = 32,
  sym_else_clause = 33,
  sym_else_open = 34,
  sym_unless_block = 35,
  sym_unless_open = 36,
  sym_unless_close = 37,
  sym_each_block = 38,
  sym_each_open = 39,
  sym_each_close = 40,
  sym_unsecure_output = 41,
  sym_include = 42,
  sym_include_args = 43,
  sym_include_arg = 44,
  sym_path = 45,
  aux_sym_template_repeat1 = 46,
  aux_sym_text_repeat1 = 47,
  aux_sym_include_args_repeat1 = 48,
  aux_sym_path_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__text_char_token1] = "_text_char_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACK] = "]",
  [anon_sym_QMARK] = "\?",
  [anon_sym_BANG] = "!",
  [anon_sym_POUND] = "#",
  [anon_sym_if] = "if",
  [anon_sym_SLASH] = "/",
  [anon_sym_else] = "else",
  [anon_sym_unless] = "unless",
  [anon_sym_each] = "each",
  [anon_sym_as] = "as",
  [anon_sym_unsecure] = "unsecure",
  [anon_sym_include] = "include",
  [anon_sym_EQ] = "=",
  [sym_delimiter_escape] = "delimiter_escape",
  [sym_tag_open] = "tag_open",
  [sym_tag_close] = "tag_close",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [sym_include_name] = "include_name",
  [sym_comment] = "comment",
  [sym__ws] = "_ws",
  [sym_template] = "template",
  [sym__node] = "_node",
  [sym_text] = "text",
  [sym__text_char] = "_text_char",
  [sym_variable] = "variable",
  [sym_modifier] = "modifier",
  [sym_if_block] = "if_block",
  [sym_if_open] = "if_open",
  [sym_if_close] = "if_close",
  [sym_else_clause] = "else_clause",
  [sym_else_open] = "else_open",
  [sym_unless_block] = "unless_block",
  [sym_unless_open] = "unless_open",
  [sym_unless_close] = "unless_close",
  [sym_each_block] = "each_block",
  [sym_each_open] = "each_open",
  [sym_each_close] = "each_close",
  [sym_unsecure_output] = "unsecure_output",
  [sym_include] = "include",
  [sym_include_args] = "include_args",
  [sym_include_arg] = "include_arg",
  [sym_path] = "path",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_text_repeat1] = "text_repeat1",
  [aux_sym_include_args_repeat1] = "include_args_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__text_char_token1] = aux_sym__text_char_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_unless] = anon_sym_unless,
  [anon_sym_each] = anon_sym_each,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_unsecure] = anon_sym_unsecure,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_delimiter_escape] = sym_delimiter_escape,
  [sym_tag_open] = sym_tag_open,
  [sym_tag_close] = sym_tag_close,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [sym_include_name] = sym_include_name,
  [sym_comment] = sym_comment,
  [sym__ws] = sym__ws,
  [sym_template] = sym_template,
  [sym__node] = sym__node,
  [sym_text] = sym_text,
  [sym__text_char] = sym__text_char,
  [sym_variable] = sym_variable,
  [sym_modifier] = sym_modifier,
  [sym_if_block] = sym_if_block,
  [sym_if_open] = sym_if_open,
  [sym_if_close] = sym_if_close,
  [sym_else_clause] = sym_else_clause,
  [sym_else_open] = sym_else_open,
  [sym_unless_block] = sym_unless_block,
  [sym_unless_open] = sym_unless_open,
  [sym_unless_close] = sym_unless_close,
  [sym_each_block] = sym_each_block,
  [sym_each_open] = sym_each_open,
  [sym_each_close] = sym_each_close,
  [sym_unsecure_output] = sym_unsecure_output,
  [sym_include] = sym_include,
  [sym_include_args] = sym_include_args,
  [sym_include_arg] = sym_include_arg,
  [sym_path] = sym_path,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
  [aux_sym_include_args_repeat1] = aux_sym_include_args_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__text_char_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_each] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unsecure] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_delimiter_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_open] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_close] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_include_name] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__text_char] = {
    .visible = false,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_if_block] = {
    .visible = true,
    .named = true,
  },
  [sym_if_open] = {
    .visible = true,
    .named = true,
  },
  [sym_if_close] = {
    .visible = true,
    .named = true,
  },
  [sym_else_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_else_open] = {
    .visible = true,
    .named = true,
  },
  [sym_unless_block] = {
    .visible = true,
    .named = true,
  },
  [sym_unless_open] = {
    .visible = true,
    .named = true,
  },
  [sym_unless_close] = {
    .visible = true,
    .named = true,
  },
  [sym_each_block] = {
    .visible = true,
    .named = true,
  },
  [sym_each_open] = {
    .visible = true,
    .named = true,
  },
  [sym_each_close] = {
    .visible = true,
    .named = true,
  },
  [sym_unsecure_output] = {
    .visible = true,
    .named = true,
  },
  [sym_include] = {
    .visible = true,
    .named = true,
  },
  [sym_include_args] = {
    .visible = true,
    .named = true,
  },
  [sym_include_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_include_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
  [156] = 156,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 160,
  [161] = 161,
  [162] = 162,
  [163] = 163,
  [164] = 164,
  [165] = 165,
  [166] = 166,
  [167] = 167,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      ADVANCE_MAP(
        '!', 38,
        '#', 39,
        '.', 60,
        '/', 42,
        '=', 55,
        '?', 37,
        ']', 36,
        'a', 77,
        'e', 61,
        'i', 71,
        'u', 75,
        '{', 35,
        '\t', 86,
        '\n', 86,
        '\r', 86,
        ' ', 86,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 38,
        '#', 39,
        '-', 5,
        '.', 60,
        '/', 42,
        '?', 37,
        ']', 30,
        '\t', 86,
        '\n', 86,
        '\r', 86,
        ' ', 86,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '/', 31,
        'a', 22,
        'e', 6,
        'i', 16,
        'u', 20,
        '\t', 86,
        '\n', 86,
        '\r', 86,
        ' ', 86,
      );
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(29);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(30);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(7);
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(40);
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 17:
      if (lookahead == 'h') ADVANCE(47);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(14);
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(49);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 28:
      if (lookahead == '}') ADVANCE(85);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 29:
      if (lookahead == '}') ADVANCE(56);
      END_STATE();
    case 30:
      if (lookahead == '}') ADVANCE(59);
      END_STATE();
    case 31:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      if (lookahead == ']') ADVANCE(36);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym__text_char_token1);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '{') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '[') ADVANCE(58);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_unless);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_unless);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_each);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_each);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_as);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_unsecure);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_unsecure);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_include);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_delimiter_escape);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_tag_open);
      if (lookahead == '%') ADVANCE(2);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_tag_open);
      if (lookahead == '%') ADVANCE(2);
      if (lookahead == '-') ADVANCE(57);
      if (lookahead == '{') ADVANCE(4);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_tag_close);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(62);
      if (lookahead == 'l') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(41);
      if (lookahead == 'n') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(69);
      if (lookahead == 's') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_include_name);
      if (lookahead == '/') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(86);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 32},
  [2] = {.lex_state = 32},
  [3] = {.lex_state = 32},
  [4] = {.lex_state = 32},
  [5] = {.lex_state = 32},
  [6] = {.lex_state = 32},
  [7] = {.lex_state = 32},
  [8] = {.lex_state = 32},
  [9] = {.lex_state = 32},
  [10] = {.lex_state = 32},
  [11] = {.lex_state = 32},
  [12] = {.lex_state = 32},
  [13] = {.lex_state = 32},
  [14] = {.lex_state = 32},
  [15] = {.lex_state = 32},
  [16] = {.lex_state = 32},
  [17] = {.lex_state = 32},
  [18] = {.lex_state = 32},
  [19] = {.lex_state = 32},
  [20] = {.lex_state = 32},
  [21] = {.lex_state = 32},
  [22] = {.lex_state = 32},
  [23] = {.lex_state = 32},
  [24] = {.lex_state = 32},
  [25] = {.lex_state = 32},
  [26] = {.lex_state = 32},
  [27] = {.lex_state = 32},
  [28] = {.lex_state = 32},
  [29] = {.lex_state = 32},
  [30] = {.lex_state = 32},
  [31] = {.lex_state = 32},
  [32] = {.lex_state = 32},
  [33] = {.lex_state = 32},
  [34] = {.lex_state = 32},
  [35] = {.lex_state = 32},
  [36] = {.lex_state = 32},
  [37] = {.lex_state = 32},
  [38] = {.lex_state = 32},
  [39] = {.lex_state = 32},
  [40] = {.lex_state = 32},
  [41] = {.lex_state = 32},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 32},
  [44] = {.lex_state = 32},
  [45] = {.lex_state = 32},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 32},
  [48] = {.lex_state = 32},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 32},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 32},
  [55] = {.lex_state = 32},
  [56] = {.lex_state = 32},
  [57] = {.lex_state = 32},
  [58] = {.lex_state = 32},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 1},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 1},
  [105] = {.lex_state = 1},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 3},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 3},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 3},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 1},
  [115] = {.lex_state = 1},
  [116] = {.lex_state = 1},
  [117] = {.lex_state = 1},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 3},
  [121] = {.lex_state = 1},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 1},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 3},
  [126] = {.lex_state = 3},
  [127] = {.lex_state = 1},
  [128] = {.lex_state = 1},
  [129] = {.lex_state = 1},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 1},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 3},
  [134] = {.lex_state = 1},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 1},
  [138] = {.lex_state = 1},
  [139] = {.lex_state = 3},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 1},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 1},
  [144] = {.lex_state = 1},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 1},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 1},
  [149] = {.lex_state = 1},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 1},
  [154] = {.lex_state = 1},
  [155] = {.lex_state = 1},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 3},
  [158] = {.lex_state = 1},
  [159] = {.lex_state = 1},
  [160] = {.lex_state = 1},
  [161] = {.lex_state = 0},
  [162] = {.lex_state = 1},
  [163] = {.lex_state = 3},
  [164] = {.lex_state = 1},
  [165] = {.lex_state = 0},
  [166] = {.lex_state = 1},
  [167] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_unless] = ACTIONS(1),
    [anon_sym_each] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_unsecure] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_delimiter_escape] = ACTIONS(1),
    [sym_tag_open] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
  },
  [1] = {
    [sym_template] = STATE(165),
    [sym__node] = STATE(7),
    [sym_text] = STATE(7),
    [sym__text_char] = STATE(12),
    [sym_variable] = STATE(7),
    [sym_if_block] = STATE(7),
    [sym_if_open] = STATE(2),
    [sym_unless_block] = STATE(7),
    [sym_unless_open] = STATE(5),
    [sym_each_block] = STATE(7),
    [sym_each_open] = STATE(6),
    [sym_unsecure_output] = STATE(7),
    [sym_include] = STATE(7),
    [aux_sym_template_repeat1] = STATE(7),
    [aux_sym_text_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym__text_char_token1] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACK] = ACTIONS(5),
    [sym_delimiter_escape] = ACTIONS(9),
    [sym_tag_open] = ACTIONS(11),
    [sym_comment] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(5), 1,
      sym_unless_open,
    STATE(6), 1,
      sym_each_open,
    STATE(11), 1,
      sym_else_open,
    STATE(21), 1,
      sym_if_close,
    STATE(82), 1,
      sym_else_clause,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(13), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(12), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(3), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [48] = 12,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(5), 1,
      sym_unless_open,
    STATE(6), 1,
      sym_each_open,
    STATE(11), 1,
      sym_else_open,
    STATE(15), 1,
      sym_if_close,
    STATE(108), 1,
      sym_else_clause,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(12), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(9), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [96] = 10,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(5), 1,
      sym_unless_open,
    STATE(6), 1,
      sym_each_open,
    STATE(36), 1,
      sym_each_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(12), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(9), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [138] = 10,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(5), 1,
      sym_unless_open,
    STATE(6), 1,
      sym_each_open,
    STATE(24), 1,
      sym_unless_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(21), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(12), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(8), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [180] = 10,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(5), 1,
      sym_unless_open,
    STATE(6), 1,
      sym_each_open,
    STATE(26), 1,
      sym_each_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(25), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(12), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(4), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [222] = 10,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_tag_open,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_if_open,
    STATE(5), 1,
      sym_unless_open,
    STATE(6), 1,
      sym_each_open,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(12), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(9), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [264] = 10,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(5), 1,
      sym_unless_open,
    STATE(6), 1,
      sym_each_open,
    STATE(38), 1,
      sym_unless_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(12), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(9), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [306] = 10,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 1,
      anon_sym_LBRACE,
    ACTIONS(40), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(5), 1,
      sym_unless_open,
    STATE(6), 1,
      sym_each_open,
    ACTIONS(31), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(37), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(12), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(9), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [348] = 9,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(5), 1,
      sym_unless_open,
    STATE(6), 1,
      sym_each_open,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(12), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(9), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [387] = 9,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(48), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(5), 1,
      sym_unless_open,
    STATE(6), 1,
      sym_each_open,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(46), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(12), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(10), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [426] = 5,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_tag_open,
    ACTIONS(53), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    STATE(13), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    ACTIONS(51), 3,
      ts_builtin_sym_end,
      sym_delimiter_escape,
      sym_comment,
  [446] = 5,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      sym_tag_open,
    ACTIONS(61), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    STATE(13), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    ACTIONS(59), 3,
      ts_builtin_sym_end,
      sym_delimiter_escape,
      sym_comment,
  [466] = 2,
    ACTIONS(71), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(69), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [478] = 2,
    ACTIONS(75), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(73), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [490] = 2,
    ACTIONS(79), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [502] = 2,
    ACTIONS(83), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(81), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [514] = 2,
    ACTIONS(87), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(85), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [526] = 2,
    ACTIONS(91), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(89), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [538] = 2,
    ACTIONS(95), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(93), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [550] = 2,
    ACTIONS(99), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(97), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [562] = 2,
    ACTIONS(103), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(101), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [574] = 2,
    ACTIONS(107), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(105), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [586] = 2,
    ACTIONS(111), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [598] = 2,
    ACTIONS(115), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(113), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [610] = 2,
    ACTIONS(119), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(117), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [622] = 2,
    ACTIONS(123), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(121), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [634] = 2,
    ACTIONS(127), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(125), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [646] = 2,
    ACTIONS(131), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(129), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [658] = 2,
    ACTIONS(135), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [670] = 2,
    ACTIONS(139), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(137), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [682] = 2,
    ACTIONS(143), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [694] = 2,
    ACTIONS(147), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(145), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [706] = 2,
    ACTIONS(151), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(149), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [718] = 2,
    ACTIONS(155), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(153), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [730] = 2,
    ACTIONS(159), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(157), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [742] = 2,
    ACTIONS(163), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(161), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [754] = 2,
    ACTIONS(167), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(165), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [766] = 2,
    ACTIONS(171), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(169), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [778] = 2,
    ACTIONS(175), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(173), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [790] = 2,
    ACTIONS(179), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(177), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [801] = 6,
    ACTIONS(181), 1,
      anon_sym_BANG,
    ACTIONS(183), 1,
      anon_sym_POUND,
    ACTIONS(185), 1,
      anon_sym_SLASH,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(189), 1,
      sym__ws,
    STATE(62), 1,
      sym_path,
  [820] = 2,
    ACTIONS(193), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(191), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [831] = 2,
    ACTIONS(197), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(195), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [842] = 2,
    ACTIONS(201), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(199), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [853] = 3,
    ACTIONS(205), 1,
      anon_sym_DOT,
    STATE(52), 1,
      aux_sym_path_repeat1,
    ACTIONS(203), 4,
      anon_sym_QMARK,
      anon_sym_BANG,
      sym_tag_close,
      sym__ws,
  [866] = 2,
    ACTIONS(209), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(207), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [877] = 2,
    ACTIONS(213), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(211), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [888] = 6,
    ACTIONS(181), 1,
      anon_sym_BANG,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(189), 1,
      sym__ws,
    ACTIONS(215), 1,
      anon_sym_POUND,
    ACTIONS(217), 1,
      anon_sym_SLASH,
    STATE(62), 1,
      sym_path,
  [907] = 2,
    ACTIONS(221), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(219), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [918] = 6,
    ACTIONS(181), 1,
      anon_sym_BANG,
    ACTIONS(183), 1,
      anon_sym_POUND,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(189), 1,
      sym__ws,
    ACTIONS(223), 1,
      anon_sym_SLASH,
    STATE(62), 1,
      sym_path,
  [937] = 3,
    ACTIONS(205), 1,
      anon_sym_DOT,
    STATE(53), 1,
      aux_sym_path_repeat1,
    ACTIONS(225), 4,
      anon_sym_QMARK,
      anon_sym_BANG,
      sym_tag_close,
      sym__ws,
  [950] = 3,
    ACTIONS(229), 1,
      anon_sym_DOT,
    STATE(53), 1,
      aux_sym_path_repeat1,
    ACTIONS(227), 4,
      anon_sym_QMARK,
      anon_sym_BANG,
      sym_tag_close,
      sym__ws,
  [963] = 2,
    ACTIONS(234), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(232), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [974] = 2,
    ACTIONS(238), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(236), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [985] = 2,
    ACTIONS(242), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(240), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [996] = 2,
    ACTIONS(246), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(244), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1007] = 2,
    ACTIONS(250), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(248), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1018] = 1,
    ACTIONS(227), 5,
      anon_sym_QMARK,
      anon_sym_BANG,
      sym_tag_close,
      anon_sym_DOT,
      sym__ws,
  [1026] = 5,
    ACTIONS(252), 1,
      anon_sym_if,
    ACTIONS(254), 1,
      anon_sym_else,
    ACTIONS(256), 1,
      anon_sym_unless,
    ACTIONS(258), 1,
      anon_sym_each,
    ACTIONS(260), 1,
      sym__ws,
  [1042] = 4,
    ACTIONS(264), 1,
      sym_tag_close,
    ACTIONS(266), 1,
      sym__ws,
    STATE(104), 1,
      sym_modifier,
    ACTIONS(262), 2,
      anon_sym_QMARK,
      anon_sym_BANG,
  [1056] = 4,
    ACTIONS(268), 1,
      sym_tag_close,
    ACTIONS(270), 1,
      sym__ws,
    STATE(106), 1,
      sym_modifier,
    ACTIONS(262), 2,
      anon_sym_QMARK,
      anon_sym_BANG,
  [1070] = 5,
    ACTIONS(181), 1,
      anon_sym_BANG,
    ACTIONS(183), 1,
      anon_sym_POUND,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(189), 1,
      sym__ws,
    STATE(62), 1,
      sym_path,
  [1086] = 4,
    ACTIONS(272), 1,
      sym_tag_close,
    ACTIONS(274), 1,
      sym__ws,
    STATE(71), 1,
      aux_sym_include_args_repeat1,
    STATE(110), 1,
      sym_include_args,
  [1099] = 4,
    ACTIONS(276), 1,
      anon_sym_if,
    ACTIONS(278), 1,
      anon_sym_else,
    ACTIONS(280), 1,
      anon_sym_unless,
    ACTIONS(282), 1,
      anon_sym_each,
  [1112] = 4,
    ACTIONS(284), 1,
      sym_tag_close,
    ACTIONS(286), 1,
      sym__ws,
    STATE(71), 1,
      aux_sym_include_args_repeat1,
    STATE(103), 1,
      sym_include_args,
  [1125] = 4,
    ACTIONS(252), 1,
      anon_sym_if,
    ACTIONS(256), 1,
      anon_sym_unless,
    ACTIONS(258), 1,
      anon_sym_each,
    ACTIONS(288), 1,
      sym__ws,
  [1138] = 3,
    ACTIONS(276), 1,
      anon_sym_if,
    ACTIONS(280), 1,
      anon_sym_unless,
    ACTIONS(282), 1,
      anon_sym_each,
  [1148] = 3,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(290), 1,
      sym__ws,
    STATE(94), 1,
      sym_path,
  [1158] = 3,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(292), 1,
      sym__ws,
    STATE(88), 1,
      sym_path,
  [1168] = 3,
    ACTIONS(294), 1,
      sym_tag_close,
    ACTIONS(296), 1,
      sym__ws,
    STATE(73), 1,
      aux_sym_include_args_repeat1,
  [1178] = 3,
    ACTIONS(272), 1,
      sym_tag_close,
    ACTIONS(299), 1,
      sym_identifier,
    STATE(117), 1,
      sym_include_arg,
  [1188] = 3,
    ACTIONS(301), 1,
      sym_tag_close,
    ACTIONS(303), 1,
      sym__ws,
    STATE(73), 1,
      aux_sym_include_args_repeat1,
  [1198] = 3,
    ACTIONS(299), 1,
      sym_identifier,
    ACTIONS(306), 1,
      sym_tag_close,
    STATE(117), 1,
      sym_include_arg,
  [1208] = 3,
    ACTIONS(308), 1,
      anon_sym_unsecure,
    ACTIONS(310), 1,
      anon_sym_include,
    ACTIONS(312), 1,
      sym__ws,
  [1218] = 2,
    ACTIONS(187), 1,
      sym_identifier,
    STATE(113), 1,
      sym_path,
  [1225] = 2,
    ACTIONS(187), 1,
      sym_identifier,
    STATE(80), 1,
      sym_path,
  [1232] = 2,
    ACTIONS(187), 1,
      sym_identifier,
    STATE(105), 1,
      sym_path,
  [1239] = 2,
    ACTIONS(187), 1,
      sym_identifier,
    STATE(61), 1,
      sym_path,
  [1246] = 2,
    ACTIONS(314), 1,
      sym_tag_close,
    ACTIONS(316), 1,
      sym__ws,
  [1253] = 2,
    ACTIONS(318), 1,
      sym_tag_close,
    ACTIONS(320), 1,
      sym__ws,
  [1260] = 2,
    ACTIONS(322), 1,
      sym_tag_open,
    STATE(15), 1,
      sym_if_close,
  [1267] = 2,
    ACTIONS(187), 1,
      sym_identifier,
    STATE(112), 1,
      sym_path,
  [1274] = 2,
    ACTIONS(187), 1,
      sym_identifier,
    STATE(132), 1,
      sym_path,
  [1281] = 1,
    ACTIONS(324), 2,
      sym_tag_close,
      sym__ws,
  [1286] = 2,
    ACTIONS(326), 1,
      sym_tag_close,
    ACTIONS(328), 1,
      sym__ws,
  [1293] = 2,
    ACTIONS(187), 1,
      sym_identifier,
    STATE(85), 1,
      sym_path,
  [1300] = 1,
    ACTIONS(330), 2,
      sym_tag_close,
      sym__ws,
  [1305] = 2,
    ACTIONS(332), 1,
      sym_tag_close,
    ACTIONS(334), 1,
      sym__ws,
  [1312] = 2,
    ACTIONS(336), 1,
      sym_tag_close,
    ACTIONS(338), 1,
      sym__ws,
  [1319] = 2,
    ACTIONS(340), 1,
      sym_tag_close,
    ACTIONS(342), 1,
      sym__ws,
  [1326] = 2,
    ACTIONS(344), 1,
      sym_tag_close,
    ACTIONS(346), 1,
      sym__ws,
  [1333] = 2,
    ACTIONS(348), 1,
      anon_sym_unsecure,
    ACTIONS(350), 1,
      anon_sym_include,
  [1340] = 1,
    ACTIONS(352), 2,
      sym_tag_close,
      sym__ws,
  [1345] = 2,
    ACTIONS(354), 1,
      sym_tag_close,
    ACTIONS(356), 1,
      sym__ws,
  [1352] = 2,
    ACTIONS(358), 1,
      sym_tag_close,
    ACTIONS(360), 1,
      sym__ws,
  [1359] = 2,
    ACTIONS(187), 1,
      sym_identifier,
    STATE(88), 1,
      sym_path,
  [1366] = 2,
    ACTIONS(362), 1,
      sym_tag_close,
    ACTIONS(364), 1,
      sym__ws,
  [1373] = 2,
    ACTIONS(366), 1,
      sym_tag_close,
    ACTIONS(368), 1,
      sym__ws,
  [1380] = 1,
    ACTIONS(370), 2,
      sym_tag_close,
      sym__ws,
  [1385] = 2,
    ACTIONS(372), 1,
      sym_tag_close,
    ACTIONS(374), 1,
      sym__ws,
  [1392] = 2,
    ACTIONS(376), 1,
      sym_tag_close,
    ACTIONS(378), 1,
      sym__ws,
  [1399] = 2,
    ACTIONS(272), 1,
      sym_tag_close,
    ACTIONS(380), 1,
      sym__ws,
  [1406] = 2,
    ACTIONS(382), 1,
      sym_tag_close,
    ACTIONS(384), 1,
      sym__ws,
  [1413] = 2,
    ACTIONS(386), 1,
      sym_tag_close,
    ACTIONS(388), 1,
      sym__ws,
  [1420] = 2,
    ACTIONS(264), 1,
      sym_tag_close,
    ACTIONS(266), 1,
      sym__ws,
  [1427] = 2,
    ACTIONS(390), 1,
      anon_sym_if,
    ACTIONS(392), 1,
      sym__ws,
  [1434] = 2,
    ACTIONS(322), 1,
      sym_tag_open,
    STATE(19), 1,
      sym_if_close,
  [1441] = 2,
    ACTIONS(394), 1,
      anon_sym_unless,
    ACTIONS(396), 1,
      sym__ws,
  [1448] = 2,
    ACTIONS(306), 1,
      sym_tag_close,
    ACTIONS(398), 1,
      sym__ws,
  [1455] = 2,
    ACTIONS(400), 1,
      anon_sym_each,
    ACTIONS(402), 1,
      sym__ws,
  [1462] = 2,
    ACTIONS(404), 1,
      sym_tag_close,
    ACTIONS(406), 1,
      sym__ws,
  [1469] = 2,
    ACTIONS(408), 1,
      sym_tag_close,
    ACTIONS(410), 1,
      sym__ws,
  [1476] = 2,
    ACTIONS(187), 1,
      sym_identifier,
    STATE(99), 1,
      sym_path,
  [1483] = 2,
    ACTIONS(299), 1,
      sym_identifier,
    STATE(117), 1,
      sym_include_arg,
  [1490] = 2,
    ACTIONS(187), 1,
      sym_identifier,
    STATE(167), 1,
      sym_path,
  [1497] = 1,
    ACTIONS(301), 2,
      sym_tag_close,
      sym__ws,
  [1502] = 2,
    ACTIONS(187), 1,
      sym_identifier,
    STATE(81), 1,
      sym_path,
  [1509] = 2,
    ACTIONS(412), 1,
      anon_sym_EQ,
    ACTIONS(414), 1,
      sym__ws,
  [1516] = 1,
    ACTIONS(416), 1,
      anon_sym_if,
  [1520] = 1,
    ACTIONS(264), 1,
      sym_tag_close,
  [1524] = 1,
    ACTIONS(418), 1,
      sym__ws,
  [1528] = 1,
    ACTIONS(420), 1,
      sym_tag_close,
  [1532] = 1,
    ACTIONS(422), 1,
      sym__ws,
  [1536] = 1,
    ACTIONS(424), 1,
      sym_include_name,
  [1540] = 1,
    ACTIONS(426), 1,
      sym_include_name,
  [1544] = 1,
    ACTIONS(428), 1,
      sym_tag_close,
  [1548] = 1,
    ACTIONS(306), 1,
      sym_tag_close,
  [1552] = 1,
    ACTIONS(430), 1,
      sym_tag_close,
  [1556] = 1,
    ACTIONS(432), 1,
      sym__ws,
  [1560] = 1,
    ACTIONS(434), 1,
      sym_tag_close,
  [1564] = 1,
    ACTIONS(436), 1,
      sym__ws,
  [1568] = 1,
    ACTIONS(438), 1,
      anon_sym_as,
  [1572] = 1,
    ACTIONS(408), 1,
      sym_tag_close,
  [1576] = 1,
    ACTIONS(440), 1,
      sym__ws,
  [1580] = 1,
    ACTIONS(442), 1,
      sym__ws,
  [1584] = 1,
    ACTIONS(444), 1,
      sym_tag_close,
  [1588] = 1,
    ACTIONS(446), 1,
      sym_tag_close,
  [1592] = 1,
    ACTIONS(448), 1,
      anon_sym_as,
  [1596] = 1,
    ACTIONS(217), 1,
      anon_sym_SLASH,
  [1600] = 1,
    ACTIONS(404), 1,
      sym_tag_close,
  [1604] = 1,
    ACTIONS(450), 1,
      sym__ws,
  [1608] = 1,
    ACTIONS(452), 1,
      sym_tag_close,
  [1612] = 1,
    ACTIONS(382), 1,
      sym_tag_close,
  [1616] = 1,
    ACTIONS(454), 1,
      anon_sym_EQ,
  [1620] = 1,
    ACTIONS(456), 1,
      sym_identifier,
  [1624] = 1,
    ACTIONS(458), 1,
      sym__ws,
  [1628] = 1,
    ACTIONS(460), 1,
      sym_tag_close,
  [1632] = 1,
    ACTIONS(462), 1,
      sym_identifier,
  [1636] = 1,
    ACTIONS(464), 1,
      sym__ws,
  [1640] = 1,
    ACTIONS(466), 1,
      sym__ws,
  [1644] = 1,
    ACTIONS(468), 1,
      sym__ws,
  [1648] = 1,
    ACTIONS(386), 1,
      sym_tag_close,
  [1652] = 1,
    ACTIONS(362), 1,
      sym_tag_close,
  [1656] = 1,
    ACTIONS(354), 1,
      sym_tag_close,
  [1660] = 1,
    ACTIONS(470), 1,
      sym__ws,
  [1664] = 1,
    ACTIONS(472), 1,
      anon_sym_unless,
  [1668] = 1,
    ACTIONS(474), 1,
      sym_identifier,
  [1672] = 1,
    ACTIONS(344), 1,
      sym_tag_close,
  [1676] = 1,
    ACTIONS(332), 1,
      sym_tag_close,
  [1680] = 1,
    ACTIONS(476), 1,
      sym__ws,
  [1684] = 1,
    ACTIONS(326), 1,
      sym_tag_close,
  [1688] = 1,
    ACTIONS(478), 1,
      anon_sym_each,
  [1692] = 1,
    ACTIONS(480), 1,
      sym_tag_close,
  [1696] = 1,
    ACTIONS(482), 1,
      ts_builtin_sym_end,
  [1700] = 1,
    ACTIONS(484), 1,
      sym_tag_close,
  [1704] = 1,
    ACTIONS(486), 1,
      sym__ws,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 138,
  [SMALL_STATE(6)] = 180,
  [SMALL_STATE(7)] = 222,
  [SMALL_STATE(8)] = 264,
  [SMALL_STATE(9)] = 306,
  [SMALL_STATE(10)] = 348,
  [SMALL_STATE(11)] = 387,
  [SMALL_STATE(12)] = 426,
  [SMALL_STATE(13)] = 446,
  [SMALL_STATE(14)] = 466,
  [SMALL_STATE(15)] = 478,
  [SMALL_STATE(16)] = 490,
  [SMALL_STATE(17)] = 502,
  [SMALL_STATE(18)] = 514,
  [SMALL_STATE(19)] = 526,
  [SMALL_STATE(20)] = 538,
  [SMALL_STATE(21)] = 550,
  [SMALL_STATE(22)] = 562,
  [SMALL_STATE(23)] = 574,
  [SMALL_STATE(24)] = 586,
  [SMALL_STATE(25)] = 598,
  [SMALL_STATE(26)] = 610,
  [SMALL_STATE(27)] = 622,
  [SMALL_STATE(28)] = 634,
  [SMALL_STATE(29)] = 646,
  [SMALL_STATE(30)] = 658,
  [SMALL_STATE(31)] = 670,
  [SMALL_STATE(32)] = 682,
  [SMALL_STATE(33)] = 694,
  [SMALL_STATE(34)] = 706,
  [SMALL_STATE(35)] = 718,
  [SMALL_STATE(36)] = 730,
  [SMALL_STATE(37)] = 742,
  [SMALL_STATE(38)] = 754,
  [SMALL_STATE(39)] = 766,
  [SMALL_STATE(40)] = 778,
  [SMALL_STATE(41)] = 790,
  [SMALL_STATE(42)] = 801,
  [SMALL_STATE(43)] = 820,
  [SMALL_STATE(44)] = 831,
  [SMALL_STATE(45)] = 842,
  [SMALL_STATE(46)] = 853,
  [SMALL_STATE(47)] = 866,
  [SMALL_STATE(48)] = 877,
  [SMALL_STATE(49)] = 888,
  [SMALL_STATE(50)] = 907,
  [SMALL_STATE(51)] = 918,
  [SMALL_STATE(52)] = 937,
  [SMALL_STATE(53)] = 950,
  [SMALL_STATE(54)] = 963,
  [SMALL_STATE(55)] = 974,
  [SMALL_STATE(56)] = 985,
  [SMALL_STATE(57)] = 996,
  [SMALL_STATE(58)] = 1007,
  [SMALL_STATE(59)] = 1018,
  [SMALL_STATE(60)] = 1026,
  [SMALL_STATE(61)] = 1042,
  [SMALL_STATE(62)] = 1056,
  [SMALL_STATE(63)] = 1070,
  [SMALL_STATE(64)] = 1086,
  [SMALL_STATE(65)] = 1099,
  [SMALL_STATE(66)] = 1112,
  [SMALL_STATE(67)] = 1125,
  [SMALL_STATE(68)] = 1138,
  [SMALL_STATE(69)] = 1148,
  [SMALL_STATE(70)] = 1158,
  [SMALL_STATE(71)] = 1168,
  [SMALL_STATE(72)] = 1178,
  [SMALL_STATE(73)] = 1188,
  [SMALL_STATE(74)] = 1198,
  [SMALL_STATE(75)] = 1208,
  [SMALL_STATE(76)] = 1218,
  [SMALL_STATE(77)] = 1225,
  [SMALL_STATE(78)] = 1232,
  [SMALL_STATE(79)] = 1239,
  [SMALL_STATE(80)] = 1246,
  [SMALL_STATE(81)] = 1253,
  [SMALL_STATE(82)] = 1260,
  [SMALL_STATE(83)] = 1267,
  [SMALL_STATE(84)] = 1274,
  [SMALL_STATE(85)] = 1281,
  [SMALL_STATE(86)] = 1286,
  [SMALL_STATE(87)] = 1293,
  [SMALL_STATE(88)] = 1300,
  [SMALL_STATE(89)] = 1305,
  [SMALL_STATE(90)] = 1312,
  [SMALL_STATE(91)] = 1319,
  [SMALL_STATE(92)] = 1326,
  [SMALL_STATE(93)] = 1333,
  [SMALL_STATE(94)] = 1340,
  [SMALL_STATE(95)] = 1345,
  [SMALL_STATE(96)] = 1352,
  [SMALL_STATE(97)] = 1359,
  [SMALL_STATE(98)] = 1366,
  [SMALL_STATE(99)] = 1373,
  [SMALL_STATE(100)] = 1380,
  [SMALL_STATE(101)] = 1385,
  [SMALL_STATE(102)] = 1392,
  [SMALL_STATE(103)] = 1399,
  [SMALL_STATE(104)] = 1406,
  [SMALL_STATE(105)] = 1413,
  [SMALL_STATE(106)] = 1420,
  [SMALL_STATE(107)] = 1427,
  [SMALL_STATE(108)] = 1434,
  [SMALL_STATE(109)] = 1441,
  [SMALL_STATE(110)] = 1448,
  [SMALL_STATE(111)] = 1455,
  [SMALL_STATE(112)] = 1462,
  [SMALL_STATE(113)] = 1469,
  [SMALL_STATE(114)] = 1476,
  [SMALL_STATE(115)] = 1483,
  [SMALL_STATE(116)] = 1490,
  [SMALL_STATE(117)] = 1497,
  [SMALL_STATE(118)] = 1502,
  [SMALL_STATE(119)] = 1509,
  [SMALL_STATE(120)] = 1516,
  [SMALL_STATE(121)] = 1520,
  [SMALL_STATE(122)] = 1524,
  [SMALL_STATE(123)] = 1528,
  [SMALL_STATE(124)] = 1532,
  [SMALL_STATE(125)] = 1536,
  [SMALL_STATE(126)] = 1540,
  [SMALL_STATE(127)] = 1544,
  [SMALL_STATE(128)] = 1548,
  [SMALL_STATE(129)] = 1552,
  [SMALL_STATE(130)] = 1556,
  [SMALL_STATE(131)] = 1560,
  [SMALL_STATE(132)] = 1564,
  [SMALL_STATE(133)] = 1568,
  [SMALL_STATE(134)] = 1572,
  [SMALL_STATE(135)] = 1576,
  [SMALL_STATE(136)] = 1580,
  [SMALL_STATE(137)] = 1584,
  [SMALL_STATE(138)] = 1588,
  [SMALL_STATE(139)] = 1592,
  [SMALL_STATE(140)] = 1596,
  [SMALL_STATE(141)] = 1600,
  [SMALL_STATE(142)] = 1604,
  [SMALL_STATE(143)] = 1608,
  [SMALL_STATE(144)] = 1612,
  [SMALL_STATE(145)] = 1616,
  [SMALL_STATE(146)] = 1620,
  [SMALL_STATE(147)] = 1624,
  [SMALL_STATE(148)] = 1628,
  [SMALL_STATE(149)] = 1632,
  [SMALL_STATE(150)] = 1636,
  [SMALL_STATE(151)] = 1640,
  [SMALL_STATE(152)] = 1644,
  [SMALL_STATE(153)] = 1648,
  [SMALL_STATE(154)] = 1652,
  [SMALL_STATE(155)] = 1656,
  [SMALL_STATE(156)] = 1660,
  [SMALL_STATE(157)] = 1664,
  [SMALL_STATE(158)] = 1668,
  [SMALL_STATE(159)] = 1672,
  [SMALL_STATE(160)] = 1676,
  [SMALL_STATE(161)] = 1680,
  [SMALL_STATE(162)] = 1684,
  [SMALL_STATE(163)] = 1688,
  [SMALL_STATE(164)] = 1692,
  [SMALL_STATE(165)] = 1696,
  [SMALL_STATE(166)] = 1700,
  [SMALL_STATE(167)] = 1704,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_else_clause, 2, 0, 0), SHIFT(63),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_else_clause, 1, 0, 0), SHIFT(63),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_block, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_block, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 5, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 5, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_close, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_close, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_close, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_close, 4, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_block, 4, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_block, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_close, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_close, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_block, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_block, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_output, 6, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_output, 6, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 6, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 6, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_block, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_block, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 4, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 4, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_block, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_block, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 9, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 9, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 6, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 6, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_close, 5, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_close, 5, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_close, 5, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_close, 5, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_output, 8, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_output, 8, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 8, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 8, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_close, 5, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_close, 5, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_output, 7, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_output, 7, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 7, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 7, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_block, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_block, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_close, 6, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_close, 6, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_block, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_block, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_close, 6, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_close, 6, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_close, 6, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_close, 6, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_open, 7, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_open, 7, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_open, 6, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_open, 6, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_open, 7, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_open, 7, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_open, 12, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_open, 12, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_open, 4, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_open, 4, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_open, 11, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_open, 11, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_open, 10, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_open, 10, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(146),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_open, 6, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_open, 6, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_open, 8, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_open, 8, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_open, 5, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_open, 5, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_open, 8, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_open, 8, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_open, 6, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_open, 6, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_args, 1, 0, 0),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_include_args, 1, 0, 0), SHIFT(115),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_include_args_repeat1, 2, 0, 0),
  [303] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_include_args_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_arg, 5, 0, 0),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(166),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_arg, 4, 0, 0),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(162),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_arg, 3, 0, 0),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [370] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modifier, 1, 0, 0),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(164),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(157),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(163),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [420] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [428] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [432] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [436] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [438] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [440] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [442] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [444] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [446] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [448] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [450] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [452] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [454] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [456] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [458] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [460] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [462] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [464] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [466] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [468] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [470] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [472] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [474] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [476] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [478] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [480] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [482] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [484] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [486] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_natsuzora(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
