#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 201
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 13
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  aux_sym__text_char_token1 = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACK = 3,
  anon_sym_QMARK = 4,
  anon_sym_BANG = 5,
  anon_sym_POUND = 6,
  anon_sym_if = 7,
  anon_sym_SLASH = 8,
  anon_sym_else = 9,
  anon_sym_unless = 10,
  anon_sym_each = 11,
  anon_sym_as = 12,
  anon_sym_COMMA = 13,
  anon_sym_unsecure = 14,
  anon_sym_include = 15,
  anon_sym_EQ = 16,
  sym_delimiter_escape = 17,
  sym_tag_open = 18,
  sym_tag_close = 19,
  anon_sym_DOT = 20,
  sym_identifier = 21,
  sym_include_name = 22,
  sym_comment = 23,
  sym__ws = 24,
  sym_template = 25,
  sym__node = 26,
  sym_text = 27,
  sym__text_char = 28,
  sym_variable = 29,
  sym_modifier = 30,
  sym_if_block = 31,
  sym_if_open = 32,
  sym_if_close = 33,
  sym_else_clause = 34,
  sym_else_open = 35,
  sym_unless_block = 36,
  sym_unless_open = 37,
  sym_unless_close = 38,
  sym_each_block = 39,
  sym_each_open = 40,
  sym_each_index = 41,
  sym_each_close = 42,
  sym_unsecure_block = 43,
  sym_unsecure_open = 44,
  sym_unsecure_close = 45,
  sym_unsecure_output = 46,
  sym_include = 47,
  sym_include_args = 48,
  sym_include_arg = 49,
  sym_path = 50,
  aux_sym_template_repeat1 = 51,
  aux_sym_text_repeat1 = 52,
  aux_sym_include_args_repeat1 = 53,
  aux_sym_path_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__text_char_token1] = "_text_char_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACK] = "]",
  [anon_sym_QMARK] = "\?",
  [anon_sym_BANG] = "!",
  [anon_sym_POUND] = "#",
  [anon_sym_if] = "if",
  [anon_sym_SLASH] = "/",
  [anon_sym_else] = "else",
  [anon_sym_unless] = "unless",
  [anon_sym_each] = "each",
  [anon_sym_as] = "as",
  [anon_sym_COMMA] = ",",
  [anon_sym_unsecure] = "unsecure",
  [anon_sym_include] = "include",
  [anon_sym_EQ] = "=",
  [sym_delimiter_escape] = "delimiter_escape",
  [sym_tag_open] = "tag_open",
  [sym_tag_close] = "tag_close",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [sym_include_name] = "include_name",
  [sym_comment] = "comment",
  [sym__ws] = "_ws",
  [sym_template] = "template",
  [sym__node] = "_node",
  [sym_text] = "text",
  [sym__text_char] = "_text_char",
  [sym_variable] = "variable",
  [sym_modifier] = "modifier",
  [sym_if_block] = "if_block",
  [sym_if_open] = "if_open",
  [sym_if_close] = "if_close",
  [sym_else_clause] = "else_clause",
  [sym_else_open] = "else_open",
  [sym_unless_block] = "unless_block",
  [sym_unless_open] = "unless_open",
  [sym_unless_close] = "unless_close",
  [sym_each_block] = "each_block",
  [sym_each_open] = "each_open",
  [sym_each_index] = "each_index",
  [sym_each_close] = "each_close",
  [sym_unsecure_block] = "unsecure_block",
  [sym_unsecure_open] = "unsecure_open",
  [sym_unsecure_close] = "unsecure_close",
  [sym_unsecure_output] = "unsecure_output",
  [sym_include] = "include",
  [sym_include_args] = "include_args",
  [sym_include_arg] = "include_arg",
  [sym_path] = "path",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_text_repeat1] = "text_repeat1",
  [aux_sym_include_args_repeat1] = "include_args_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__text_char_token1] = aux_sym__text_char_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_unless] = anon_sym_unless,
  [anon_sym_each] = anon_sym_each,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_unsecure] = anon_sym_unsecure,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_delimiter_escape] = sym_delimiter_escape,
  [sym_tag_open] = sym_tag_open,
  [sym_tag_close] = sym_tag_close,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [sym_include_name] = sym_include_name,
  [sym_comment] = sym_comment,
  [sym__ws] = sym__ws,
  [sym_template] = sym_template,
  [sym__node] = sym__node,
  [sym_text] = sym_text,
  [sym__text_char] = sym__text_char,
  [sym_variable] = sym_variable,
  [sym_modifier] = sym_modifier,
  [sym_if_block] = sym_if_block,
  [sym_if_open] = sym_if_open,
  [sym_if_close] = sym_if_close,
  [sym_else_clause] = sym_else_clause,
  [sym_else_open] = sym_else_open,
  [sym_unless_block] = sym_unless_block,
  [sym_unless_open] = sym_unless_open,
  [sym_unless_close] = sym_unless_close,
  [sym_each_block] = sym_each_block,
  [sym_each_open] = sym_each_open,
  [sym_each_index] = sym_each_index,
  [sym_each_close] = sym_each_close,
  [sym_unsecure_block] = sym_unsecure_block,
  [sym_unsecure_open] = sym_unsecure_open,
  [sym_unsecure_close] = sym_unsecure_close,
  [sym_unsecure_output] = sym_unsecure_output,
  [sym_include] = sym_include,
  [sym_include_args] = sym_include_args,
  [sym_include_arg] = sym_include_arg,
  [sym_path] = sym_path,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
  [aux_sym_include_args_repeat1] = aux_sym_include_args_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__text_char_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_each] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unsecure] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_delimiter_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_open] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_close] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_include_name] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__text_char] = {
    .visible = false,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_if_block] = {
    .visible = true,
    .named = true,
  },
  [sym_if_open] = {
    .visible = true,
    .named = true,
  },
  [sym_if_close] = {
    .visible = true,
    .named = true,
  },
  [sym_else_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_else_open] = {
    .visible = true,
    .named = true,
  },
  [sym_unless_block] = {
    .visible = true,
    .named = true,
  },
  [sym_unless_open] = {
    .visible = true,
    .named = true,
  },
  [sym_unless_close] = {
    .visible = true,
    .named = true,
  },
  [sym_each_block] = {
    .visible = true,
    .named = true,
  },
  [sym_each_open] = {
    .visible = true,
    .named = true,
  },
  [sym_each_index] = {
    .visible = true,
    .named = true,
  },
  [sym_each_close] = {
    .visible = true,
    .named = true,
  },
  [sym_unsecure_block] = {
    .visible = true,
    .named = true,
  },
  [sym_unsecure_open] = {
    .visible = true,
    .named = true,
  },
  [sym_unsecure_close] = {
    .visible = true,
    .named = true,
  },
  [sym_unsecure_output] = {
    .visible = true,
    .named = true,
  },
  [sym_include] = {
    .visible = true,
    .named = true,
  },
  [sym_include_args] = {
    .visible = true,
    .named = true,
  },
  [sym_include_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_include_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
  [156] = 156,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 160,
  [161] = 161,
  [162] = 162,
  [163] = 163,
  [164] = 164,
  [165] = 165,
  [166] = 166,
  [167] = 167,
  [168] = 168,
  [169] = 169,
  [170] = 170,
  [171] = 171,
  [172] = 172,
  [173] = 173,
  [174] = 174,
  [175] = 175,
  [176] = 176,
  [177] = 177,
  [178] = 178,
  [179] = 179,
  [180] = 180,
  [181] = 181,
  [182] = 182,
  [183] = 183,
  [184] = 184,
  [185] = 185,
  [186] = 186,
  [187] = 187,
  [188] = 188,
  [189] = 189,
  [190] = 190,
  [191] = 191,
  [192] = 192,
  [193] = 193,
  [194] = 194,
  [195] = 195,
  [196] = 196,
  [197] = 197,
  [198] = 198,
  [199] = 199,
  [200] = 200,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      ADVANCE_MAP(
        '!', 38,
        '#', 39,
        ',', 51,
        '.', 61,
        '/', 42,
        '=', 56,
        '?', 37,
        ']', 36,
        'a', 78,
        'e', 62,
        'i', 72,
        'u', 76,
        '{', 35,
        '\t', 87,
        '\n', 87,
        '\r', 87,
        ' ', 87,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 38,
        '#', 39,
        '-', 5,
        '/', 42,
        ']', 30,
        '\t', 87,
        '\n', 87,
        '\r', 87,
        ' ', 87,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 38,
        ',', 51,
        '-', 5,
        '.', 61,
        '/', 31,
        '?', 37,
        ']', 30,
        'a', 22,
        'e', 6,
        'i', 16,
        'u', 20,
        '\t', 87,
        '\n', 87,
        '\r', 87,
        ' ', 87,
      );
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(29);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(30);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(7);
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(40);
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 17:
      if (lookahead == 'h') ADVANCE(47);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(14);
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(49);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 28:
      if (lookahead == '}') ADVANCE(86);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 29:
      if (lookahead == '}') ADVANCE(57);
      END_STATE();
    case 30:
      if (lookahead == '}') ADVANCE(60);
      END_STATE();
    case 31:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      if (lookahead == ']') ADVANCE(36);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym__text_char_token1);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '{') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '[') ADVANCE(59);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_unless);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_unless);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_each);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_each);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_as);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_unsecure);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_unsecure);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_include);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_delimiter_escape);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_tag_open);
      if (lookahead == '%') ADVANCE(3);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_tag_open);
      if (lookahead == '%') ADVANCE(3);
      if (lookahead == '-') ADVANCE(58);
      if (lookahead == '{') ADVANCE(4);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_tag_close);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(63);
      if (lookahead == 'l') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(41);
      if (lookahead == 'n') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(70);
      if (lookahead == 's') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_include_name);
      if (lookahead == '/') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(87);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 32},
  [2] = {.lex_state = 32},
  [3] = {.lex_state = 32},
  [4] = {.lex_state = 32},
  [5] = {.lex_state = 32},
  [6] = {.lex_state = 32},
  [7] = {.lex_state = 32},
  [8] = {.lex_state = 32},
  [9] = {.lex_state = 32},
  [10] = {.lex_state = 32},
  [11] = {.lex_state = 32},
  [12] = {.lex_state = 32},
  [13] = {.lex_state = 32},
  [14] = {.lex_state = 32},
  [15] = {.lex_state = 32},
  [16] = {.lex_state = 32},
  [17] = {.lex_state = 32},
  [18] = {.lex_state = 32},
  [19] = {.lex_state = 32},
  [20] = {.lex_state = 32},
  [21] = {.lex_state = 32},
  [22] = {.lex_state = 32},
  [23] = {.lex_state = 32},
  [24] = {.lex_state = 32},
  [25] = {.lex_state = 32},
  [26] = {.lex_state = 32},
  [27] = {.lex_state = 32},
  [28] = {.lex_state = 32},
  [29] = {.lex_state = 32},
  [30] = {.lex_state = 32},
  [31] = {.lex_state = 32},
  [32] = {.lex_state = 32},
  [33] = {.lex_state = 32},
  [34] = {.lex_state = 32},
  [35] = {.lex_state = 32},
  [36] = {.lex_state = 32},
  [37] = {.lex_state = 32},
  [38] = {.lex_state = 32},
  [39] = {.lex_state = 32},
  [40] = {.lex_state = 32},
  [41] = {.lex_state = 32},
  [42] = {.lex_state = 32},
  [43] = {.lex_state = 32},
  [44] = {.lex_state = 32},
  [45] = {.lex_state = 32},
  [46] = {.lex_state = 32},
  [47] = {.lex_state = 32},
  [48] = {.lex_state = 32},
  [49] = {.lex_state = 32},
  [50] = {.lex_state = 32},
  [51] = {.lex_state = 32},
  [52] = {.lex_state = 32},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 32},
  [55] = {.lex_state = 32},
  [56] = {.lex_state = 32},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 32},
  [60] = {.lex_state = 32},
  [61] = {.lex_state = 32},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 32},
  [66] = {.lex_state = 32},
  [67] = {.lex_state = 32},
  [68] = {.lex_state = 32},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 32},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 1},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 2},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 2},
  [109] = {.lex_state = 2},
  [110] = {.lex_state = 2},
  [111] = {.lex_state = 2},
  [112] = {.lex_state = 2},
  [113] = {.lex_state = 2},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 2},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 2},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 2},
  [120] = {.lex_state = 2},
  [121] = {.lex_state = 2},
  [122] = {.lex_state = 2},
  [123] = {.lex_state = 2},
  [124] = {.lex_state = 2},
  [125] = {.lex_state = 2},
  [126] = {.lex_state = 2},
  [127] = {.lex_state = 2},
  [128] = {.lex_state = 2},
  [129] = {.lex_state = 2},
  [130] = {.lex_state = 2},
  [131] = {.lex_state = 2},
  [132] = {.lex_state = 1},
  [133] = {.lex_state = 2},
  [134] = {.lex_state = 1},
  [135] = {.lex_state = 2},
  [136] = {.lex_state = 2},
  [137] = {.lex_state = 1},
  [138] = {.lex_state = 1},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 2},
  [142] = {.lex_state = 1},
  [143] = {.lex_state = 2},
  [144] = {.lex_state = 2},
  [145] = {.lex_state = 2},
  [146] = {.lex_state = 2},
  [147] = {.lex_state = 2},
  [148] = {.lex_state = 2},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 2},
  [151] = {.lex_state = 2},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 2},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 2},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 2},
  [158] = {.lex_state = 2},
  [159] = {.lex_state = 2},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 0},
  [162] = {.lex_state = 0},
  [163] = {.lex_state = 2},
  [164] = {.lex_state = 2},
  [165] = {.lex_state = 0},
  [166] = {.lex_state = 0},
  [167] = {.lex_state = 2},
  [168] = {.lex_state = 2},
  [169] = {.lex_state = 2},
  [170] = {.lex_state = 1},
  [171] = {.lex_state = 2},
  [172] = {.lex_state = 0},
  [173] = {.lex_state = 0},
  [174] = {.lex_state = 2},
  [175] = {.lex_state = 0},
  [176] = {.lex_state = 2},
  [177] = {.lex_state = 0},
  [178] = {.lex_state = 0},
  [179] = {.lex_state = 1},
  [180] = {.lex_state = 2},
  [181] = {.lex_state = 2},
  [182] = {.lex_state = 2},
  [183] = {.lex_state = 0},
  [184] = {.lex_state = 1},
  [185] = {.lex_state = 2},
  [186] = {.lex_state = 2},
  [187] = {.lex_state = 2},
  [188] = {.lex_state = 0},
  [189] = {.lex_state = 1},
  [190] = {.lex_state = 2},
  [191] = {.lex_state = 2},
  [192] = {.lex_state = 2},
  [193] = {.lex_state = 2},
  [194] = {.lex_state = 2},
  [195] = {.lex_state = 2},
  [196] = {.lex_state = 1},
  [197] = {.lex_state = 2},
  [198] = {.lex_state = 2},
  [199] = {.lex_state = 0},
  [200] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_unless] = ACTIONS(1),
    [anon_sym_each] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_unsecure] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_delimiter_escape] = ACTIONS(1),
    [sym_tag_open] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
  },
  [1] = {
    [sym_template] = STATE(177),
    [sym__node] = STATE(7),
    [sym_text] = STATE(7),
    [sym__text_char] = STATE(14),
    [sym_variable] = STATE(7),
    [sym_if_block] = STATE(7),
    [sym_if_open] = STATE(2),
    [sym_unless_block] = STATE(7),
    [sym_unless_open] = STATE(4),
    [sym_each_block] = STATE(7),
    [sym_each_open] = STATE(5),
    [sym_unsecure_block] = STATE(7),
    [sym_unsecure_open] = STATE(6),
    [sym_unsecure_output] = STATE(7),
    [sym_include] = STATE(7),
    [aux_sym_template_repeat1] = STATE(7),
    [aux_sym_text_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym__text_char_token1] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACK] = ACTIONS(5),
    [sym_delimiter_escape] = ACTIONS(9),
    [sym_tag_open] = ACTIONS(11),
    [sym_comment] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(12), 1,
      sym_else_open,
    STATE(18), 1,
      sym_if_close,
    STATE(139), 1,
      sym_else_clause,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(13), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(3), 10,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [52] = 13,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(12), 1,
      sym_else_open,
    STATE(41), 1,
      sym_if_close,
    STATE(118), 1,
      sym_else_clause,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(8), 10,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [104] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(21), 1,
      sym_unless_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(19), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(11), 10,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [150] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(16), 1,
      sym_each_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(10), 10,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [196] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(27), 1,
      sym_unsecure_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(27), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(9), 10,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [242] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_tag_open,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(8), 10,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [288] = 11,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(44), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    ACTIONS(35), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(41), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(8), 10,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [334] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(45), 1,
      sym_unsecure_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(8), 10,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [380] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(24), 1,
      sym_each_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(8), 10,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [426] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(46), 1,
      sym_unless_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(8), 10,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [472] = 10,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(47), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(13), 10,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [515] = 10,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_delimiter_escape,
      sym_comment,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(8), 10,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_unsecure_output,
      sym_include,
      aux_sym_template_repeat1,
  [558] = 5,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_tag_open,
    ACTIONS(57), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      sym_delimiter_escape,
      sym_comment,
  [578] = 5,
    ACTIONS(68), 1,
      anon_sym_LBRACE,
    ACTIONS(71), 1,
      sym_tag_open,
    ACTIONS(65), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    ACTIONS(63), 3,
      ts_builtin_sym_end,
      sym_delimiter_escape,
      sym_comment,
  [598] = 2,
    ACTIONS(75), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(73), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [610] = 2,
    ACTIONS(79), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [622] = 2,
    ACTIONS(83), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(81), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [634] = 2,
    ACTIONS(87), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(85), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [646] = 2,
    ACTIONS(91), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(89), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [658] = 2,
    ACTIONS(95), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(93), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [670] = 2,
    ACTIONS(99), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(97), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [682] = 2,
    ACTIONS(103), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(101), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [694] = 2,
    ACTIONS(107), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(105), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [706] = 2,
    ACTIONS(111), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [718] = 2,
    ACTIONS(115), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(113), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [730] = 2,
    ACTIONS(119), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(117), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [742] = 2,
    ACTIONS(123), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(121), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [754] = 2,
    ACTIONS(127), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(125), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [766] = 2,
    ACTIONS(131), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(129), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [778] = 2,
    ACTIONS(135), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [790] = 2,
    ACTIONS(139), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(137), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [802] = 2,
    ACTIONS(143), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [814] = 2,
    ACTIONS(147), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(145), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [826] = 2,
    ACTIONS(151), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(149), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [838] = 2,
    ACTIONS(155), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(153), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [850] = 2,
    ACTIONS(159), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(157), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [862] = 2,
    ACTIONS(163), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(161), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [874] = 2,
    ACTIONS(167), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(165), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [886] = 2,
    ACTIONS(171), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(169), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [898] = 2,
    ACTIONS(175), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(173), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [910] = 2,
    ACTIONS(179), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(177), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [922] = 2,
    ACTIONS(183), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(181), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [934] = 2,
    ACTIONS(187), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(185), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [946] = 2,
    ACTIONS(191), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(189), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [958] = 2,
    ACTIONS(195), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(193), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [970] = 2,
    ACTIONS(199), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(197), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [982] = 2,
    ACTIONS(203), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(201), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [993] = 2,
    ACTIONS(207), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(205), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1004] = 2,
    ACTIONS(211), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(209), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1015] = 2,
    ACTIONS(215), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(213), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1026] = 2,
    ACTIONS(219), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(217), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1037] = 6,
    ACTIONS(221), 1,
      anon_sym_if,
    ACTIONS(223), 1,
      anon_sym_else,
    ACTIONS(225), 1,
      anon_sym_unless,
    ACTIONS(227), 1,
      anon_sym_each,
    ACTIONS(229), 1,
      anon_sym_unsecure,
    ACTIONS(231), 1,
      sym__ws,
  [1056] = 2,
    ACTIONS(235), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(233), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1067] = 2,
    ACTIONS(239), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(237), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1078] = 2,
    ACTIONS(243), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(241), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1089] = 3,
    ACTIONS(247), 1,
      anon_sym_DOT,
    STATE(69), 1,
      aux_sym_path_repeat1,
    ACTIONS(245), 4,
      anon_sym_QMARK,
      anon_sym_BANG,
      sym_tag_close,
      sym__ws,
  [1102] = 6,
    ACTIONS(249), 1,
      anon_sym_BANG,
    ACTIONS(251), 1,
      anon_sym_POUND,
    ACTIONS(253), 1,
      anon_sym_SLASH,
    ACTIONS(255), 1,
      sym_identifier,
    ACTIONS(257), 1,
      sym__ws,
    STATE(72), 1,
      sym_path,
  [1121] = 2,
    ACTIONS(261), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(259), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1132] = 2,
    ACTIONS(265), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(263), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1143] = 2,
    ACTIONS(269), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(267), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1154] = 6,
    ACTIONS(249), 1,
      anon_sym_BANG,
    ACTIONS(255), 1,
      sym_identifier,
    ACTIONS(257), 1,
      sym__ws,
    ACTIONS(271), 1,
      anon_sym_POUND,
    ACTIONS(273), 1,
      anon_sym_SLASH,
    STATE(72), 1,
      sym_path,
  [1173] = 6,
    ACTIONS(249), 1,
      anon_sym_BANG,
    ACTIONS(255), 1,
      sym_identifier,
    ACTIONS(257), 1,
      sym__ws,
    ACTIONS(271), 1,
      anon_sym_POUND,
    ACTIONS(275), 1,
      anon_sym_SLASH,
    STATE(72), 1,
      sym_path,
  [1192] = 6,
    ACTIONS(249), 1,
      anon_sym_BANG,
    ACTIONS(255), 1,
      sym_identifier,
    ACTIONS(257), 1,
      sym__ws,
    ACTIONS(271), 1,
      anon_sym_POUND,
    ACTIONS(277), 1,
      anon_sym_SLASH,
    STATE(72), 1,
      sym_path,
  [1211] = 2,
    ACTIONS(281), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(279), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1222] = 2,
    ACTIONS(285), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(283), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1233] = 2,
    ACTIONS(289), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(287), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1244] = 2,
    ACTIONS(293), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(291), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1255] = 3,
    ACTIONS(247), 1,
      anon_sym_DOT,
    STATE(70), 1,
      aux_sym_path_repeat1,
    ACTIONS(295), 4,
      anon_sym_QMARK,
      anon_sym_BANG,
      sym_tag_close,
      sym__ws,
  [1268] = 3,
    ACTIONS(299), 1,
      anon_sym_DOT,
    STATE(70), 1,
      aux_sym_path_repeat1,
    ACTIONS(297), 4,
      anon_sym_QMARK,
      anon_sym_BANG,
      sym_tag_close,
      sym__ws,
  [1281] = 2,
    ACTIONS(304), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(302), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_delimiter_escape,
      sym_comment,
  [1292] = 4,
    ACTIONS(308), 1,
      sym_tag_close,
    ACTIONS(310), 1,
      sym__ws,
    STATE(144), 1,
      sym_modifier,
    ACTIONS(306), 2,
      anon_sym_QMARK,
      anon_sym_BANG,
  [1306] = 4,
    ACTIONS(312), 1,
      sym_tag_close,
    ACTIONS(314), 1,
      sym__ws,
    STATE(128), 1,
      sym_modifier,
    ACTIONS(306), 2,
      anon_sym_QMARK,
      anon_sym_BANG,
  [1320] = 1,
    ACTIONS(297), 5,
      anon_sym_QMARK,
      anon_sym_BANG,
      sym_tag_close,
      anon_sym_DOT,
      sym__ws,
  [1328] = 5,
    ACTIONS(221), 1,
      anon_sym_if,
    ACTIONS(225), 1,
      anon_sym_unless,
    ACTIONS(227), 1,
      anon_sym_each,
    ACTIONS(229), 1,
      anon_sym_unsecure,
    ACTIONS(316), 1,
      sym__ws,
  [1344] = 5,
    ACTIONS(318), 1,
      anon_sym_if,
    ACTIONS(320), 1,
      anon_sym_else,
    ACTIONS(322), 1,
      anon_sym_unless,
    ACTIONS(324), 1,
      anon_sym_each,
    ACTIONS(326), 1,
      anon_sym_unsecure,
  [1360] = 5,
    ACTIONS(249), 1,
      anon_sym_BANG,
    ACTIONS(255), 1,
      sym_identifier,
    ACTIONS(257), 1,
      sym__ws,
    ACTIONS(271), 1,
      anon_sym_POUND,
    STATE(72), 1,
      sym_path,
  [1376] = 4,
    ACTIONS(328), 1,
      anon_sym_COMMA,
    ACTIONS(330), 1,
      sym_tag_close,
    ACTIONS(332), 1,
      sym__ws,
    STATE(124), 1,
      sym_each_index,
  [1389] = 4,
    ACTIONS(334), 1,
      sym_tag_close,
    ACTIONS(336), 1,
      sym__ws,
    STATE(87), 1,
      aux_sym_include_args_repeat1,
    STATE(145), 1,
      sym_include_args,
  [1402] = 4,
    ACTIONS(328), 1,
      anon_sym_COMMA,
    ACTIONS(338), 1,
      sym_tag_close,
    ACTIONS(340), 1,
      sym__ws,
    STATE(103), 1,
      sym_each_index,
  [1415] = 4,
    ACTIONS(342), 1,
      sym_tag_close,
    ACTIONS(344), 1,
      sym__ws,
    STATE(87), 1,
      aux_sym_include_args_repeat1,
    STATE(121), 1,
      sym_include_args,
  [1428] = 4,
    ACTIONS(318), 1,
      anon_sym_if,
    ACTIONS(322), 1,
      anon_sym_unless,
    ACTIONS(324), 1,
      anon_sym_each,
    ACTIONS(326), 1,
      anon_sym_unsecure,
  [1441] = 3,
    ACTIONS(346), 1,
      sym_tag_close,
    ACTIONS(348), 1,
      sym_identifier,
    STATE(141), 1,
      sym_include_arg,
  [1451] = 3,
    ACTIONS(350), 1,
      sym_tag_close,
    ACTIONS(352), 1,
      sym__ws,
    STATE(84), 1,
      aux_sym_include_args_repeat1,
  [1461] = 3,
    ACTIONS(255), 1,
      sym_identifier,
    ACTIONS(355), 1,
      sym__ws,
    STATE(115), 1,
      sym_path,
  [1471] = 3,
    ACTIONS(357), 1,
      anon_sym_unsecure,
    ACTIONS(359), 1,
      anon_sym_include,
    ACTIONS(361), 1,
      sym__ws,
  [1481] = 3,
    ACTIONS(363), 1,
      sym_tag_close,
    ACTIONS(365), 1,
      sym__ws,
    STATE(84), 1,
      aux_sym_include_args_repeat1,
  [1491] = 3,
    ACTIONS(334), 1,
      sym_tag_close,
    ACTIONS(348), 1,
      sym_identifier,
    STATE(141), 1,
      sym_include_arg,
  [1501] = 3,
    ACTIONS(255), 1,
      sym_identifier,
    ACTIONS(368), 1,
      sym__ws,
    STATE(109), 1,
      sym_path,
  [1511] = 2,
    ACTIONS(370), 1,
      sym_tag_close,
    ACTIONS(372), 1,
      sym__ws,
  [1518] = 2,
    ACTIONS(255), 1,
      sym_identifier,
    STATE(109), 1,
      sym_path,
  [1525] = 2,
    ACTIONS(374), 1,
      sym_tag_close,
    ACTIONS(376), 1,
      sym__ws,
  [1532] = 2,
    ACTIONS(378), 1,
      sym_identifier,
    ACTIONS(380), 1,
      sym__ws,
  [1539] = 2,
    ACTIONS(255), 1,
      sym_identifier,
    STATE(90), 1,
      sym_path,
  [1546] = 2,
    ACTIONS(255), 1,
      sym_identifier,
    STATE(123), 1,
      sym_path,
  [1553] = 1,
    ACTIONS(382), 2,
      sym_tag_close,
      sym__ws,
  [1558] = 2,
    ACTIONS(384), 1,
      sym_tag_close,
    ACTIONS(386), 1,
      sym__ws,
  [1565] = 2,
    ACTIONS(388), 1,
      sym_tag_close,
    ACTIONS(390), 1,
      sym__ws,
  [1572] = 1,
    ACTIONS(392), 2,
      sym_tag_close,
      sym__ws,
  [1577] = 2,
    ACTIONS(255), 1,
      sym_identifier,
    STATE(129), 1,
      sym_path,
  [1584] = 2,
    ACTIONS(255), 1,
      sym_identifier,
    STATE(130), 1,
      sym_path,
  [1591] = 2,
    ACTIONS(255), 1,
      sym_identifier,
    STATE(165), 1,
      sym_path,
  [1598] = 2,
    ACTIONS(330), 1,
      sym_tag_close,
    ACTIONS(394), 1,
      sym__ws,
  [1605] = 2,
    ACTIONS(330), 1,
      sym_tag_close,
    ACTIONS(396), 1,
      anon_sym_COMMA,
  [1612] = 2,
    ACTIONS(398), 1,
      sym_tag_close,
    ACTIONS(400), 1,
      sym__ws,
  [1619] = 2,
    ACTIONS(402), 1,
      sym_identifier,
    ACTIONS(404), 1,
      sym__ws,
  [1626] = 2,
    ACTIONS(255), 1,
      sym_identifier,
    STATE(99), 1,
      sym_path,
  [1633] = 2,
    ACTIONS(406), 1,
      sym_tag_close,
    ACTIONS(408), 1,
      sym__ws,
  [1640] = 1,
    ACTIONS(410), 2,
      sym_tag_close,
      sym__ws,
  [1645] = 2,
    ACTIONS(412), 1,
      sym_tag_close,
    ACTIONS(414), 1,
      sym__ws,
  [1652] = 2,
    ACTIONS(416), 1,
      sym_tag_close,
    ACTIONS(418), 1,
      sym__ws,
  [1659] = 1,
    ACTIONS(420), 2,
      sym_tag_close,
      sym__ws,
  [1664] = 2,
    ACTIONS(422), 1,
      sym_tag_close,
    ACTIONS(424), 1,
      sym__ws,
  [1671] = 2,
    ACTIONS(426), 1,
      sym_tag_close,
    ACTIONS(428), 1,
      sym__ws,
  [1678] = 1,
    ACTIONS(430), 2,
      sym_tag_close,
      sym__ws,
  [1683] = 2,
    ACTIONS(432), 1,
      sym_tag_close,
    ACTIONS(434), 1,
      sym__ws,
  [1690] = 2,
    ACTIONS(436), 1,
      anon_sym_if,
    ACTIONS(438), 1,
      sym__ws,
  [1697] = 2,
    ACTIONS(440), 1,
      sym_tag_open,
    STATE(47), 1,
      sym_if_close,
  [1704] = 2,
    ACTIONS(442), 1,
      anon_sym_unless,
    ACTIONS(444), 1,
      sym__ws,
  [1711] = 2,
    ACTIONS(396), 1,
      anon_sym_COMMA,
    ACTIONS(446), 1,
      sym_tag_close,
  [1718] = 2,
    ACTIONS(334), 1,
      sym_tag_close,
    ACTIONS(448), 1,
      sym__ws,
  [1725] = 2,
    ACTIONS(450), 1,
      sym_tag_close,
    ACTIONS(452), 1,
      sym__ws,
  [1732] = 2,
    ACTIONS(454), 1,
      sym_tag_close,
    ACTIONS(456), 1,
      sym__ws,
  [1739] = 2,
    ACTIONS(446), 1,
      sym_tag_close,
    ACTIONS(458), 1,
      sym__ws,
  [1746] = 2,
    ACTIONS(460), 1,
      sym_tag_close,
    ACTIONS(462), 1,
      sym__ws,
  [1753] = 1,
    ACTIONS(464), 2,
      sym_tag_close,
      sym__ws,
  [1758] = 2,
    ACTIONS(466), 1,
      sym_tag_close,
    ACTIONS(468), 1,
      sym__ws,
  [1765] = 2,
    ACTIONS(470), 1,
      sym_tag_close,
    ACTIONS(472), 1,
      sym__ws,
  [1772] = 2,
    ACTIONS(474), 1,
      sym_tag_close,
    ACTIONS(476), 1,
      sym__ws,
  [1779] = 2,
    ACTIONS(478), 1,
      sym_tag_close,
    ACTIONS(480), 1,
      sym__ws,
  [1786] = 2,
    ACTIONS(482), 1,
      anon_sym_each,
    ACTIONS(484), 1,
      sym__ws,
  [1793] = 2,
    ACTIONS(255), 1,
      sym_identifier,
    STATE(73), 1,
      sym_path,
  [1800] = 2,
    ACTIONS(486), 1,
      anon_sym_unsecure,
    ACTIONS(488), 1,
      anon_sym_include,
  [1807] = 2,
    ACTIONS(255), 1,
      sym_identifier,
    STATE(188), 1,
      sym_path,
  [1814] = 1,
    ACTIONS(490), 2,
      sym_tag_close,
      sym__ws,
  [1819] = 2,
    ACTIONS(492), 1,
      anon_sym_unsecure,
    ACTIONS(494), 1,
      sym__ws,
  [1826] = 2,
    ACTIONS(255), 1,
      sym_identifier,
    STATE(98), 1,
      sym_path,
  [1833] = 2,
    ACTIONS(255), 1,
      sym_identifier,
    STATE(97), 1,
      sym_path,
  [1840] = 2,
    ACTIONS(440), 1,
      sym_tag_open,
    STATE(41), 1,
      sym_if_close,
  [1847] = 2,
    ACTIONS(496), 1,
      anon_sym_EQ,
    ACTIONS(498), 1,
      sym__ws,
  [1854] = 1,
    ACTIONS(350), 2,
      sym_tag_close,
      sym__ws,
  [1859] = 2,
    ACTIONS(348), 1,
      sym_identifier,
    STATE(141), 1,
      sym_include_arg,
  [1866] = 2,
    ACTIONS(500), 1,
      sym_tag_close,
    ACTIONS(502), 1,
      sym__ws,
  [1873] = 2,
    ACTIONS(312), 1,
      sym_tag_close,
    ACTIONS(314), 1,
      sym__ws,
  [1880] = 2,
    ACTIONS(346), 1,
      sym_tag_close,
    ACTIONS(504), 1,
      sym__ws,
  [1887] = 1,
    ACTIONS(506), 1,
      sym_tag_close,
  [1891] = 1,
    ACTIONS(508), 1,
      sym_tag_close,
  [1895] = 1,
    ACTIONS(346), 1,
      sym_tag_close,
  [1899] = 1,
    ACTIONS(510), 1,
      sym__ws,
  [1903] = 1,
    ACTIONS(512), 1,
      sym_tag_close,
  [1907] = 1,
    ACTIONS(514), 1,
      sym_tag_close,
  [1911] = 1,
    ACTIONS(516), 1,
      sym__ws,
  [1915] = 1,
    ACTIONS(518), 1,
      sym_tag_close,
  [1919] = 1,
    ACTIONS(520), 1,
      sym__ws,
  [1923] = 1,
    ACTIONS(522), 1,
      sym_include_name,
  [1927] = 1,
    ACTIONS(524), 1,
      sym__ws,
  [1931] = 1,
    ACTIONS(526), 1,
      sym_tag_close,
  [1935] = 1,
    ACTIONS(528), 1,
      sym_tag_close,
  [1939] = 1,
    ACTIONS(530), 1,
      anon_sym_as,
  [1943] = 1,
    ACTIONS(532), 1,
      sym__ws,
  [1947] = 1,
    ACTIONS(534), 1,
      sym__ws,
  [1951] = 1,
    ACTIONS(536), 1,
      sym__ws,
  [1955] = 1,
    ACTIONS(538), 1,
      sym_tag_close,
  [1959] = 1,
    ACTIONS(500), 1,
      sym_tag_close,
  [1963] = 1,
    ACTIONS(540), 1,
      sym__ws,
  [1967] = 1,
    ACTIONS(542), 1,
      anon_sym_EQ,
  [1971] = 1,
    ACTIONS(544), 1,
      anon_sym_as,
  [1975] = 1,
    ACTIONS(478), 1,
      sym_tag_close,
  [1979] = 1,
    ACTIONS(546), 1,
      sym_tag_close,
  [1983] = 1,
    ACTIONS(548), 1,
      sym_identifier,
  [1987] = 1,
    ACTIONS(474), 1,
      sym_tag_close,
  [1991] = 1,
    ACTIONS(550), 1,
      sym__ws,
  [1995] = 1,
    ACTIONS(552), 1,
      sym__ws,
  [1999] = 1,
    ACTIONS(454), 1,
      sym_tag_close,
  [2003] = 1,
    ACTIONS(554), 1,
      sym__ws,
  [2007] = 1,
    ACTIONS(432), 1,
      sym_tag_close,
  [2011] = 1,
    ACTIONS(556), 1,
      ts_builtin_sym_end,
  [2015] = 1,
    ACTIONS(558), 1,
      sym__ws,
  [2019] = 1,
    ACTIONS(560), 1,
      sym_identifier,
  [2023] = 1,
    ACTIONS(422), 1,
      sym_tag_close,
  [2027] = 1,
    ACTIONS(412), 1,
      sym_tag_close,
  [2031] = 1,
    ACTIONS(406), 1,
      sym_tag_close,
  [2035] = 1,
    ACTIONS(253), 1,
      anon_sym_SLASH,
  [2039] = 1,
    ACTIONS(562), 1,
      sym_identifier,
  [2043] = 1,
    ACTIONS(398), 1,
      sym_tag_close,
  [2047] = 1,
    ACTIONS(564), 1,
      sym_tag_close,
  [2051] = 1,
    ACTIONS(566), 1,
      sym_tag_close,
  [2055] = 1,
    ACTIONS(568), 1,
      sym__ws,
  [2059] = 1,
    ACTIONS(378), 1,
      sym_identifier,
  [2063] = 1,
    ACTIONS(570), 1,
      sym_include_name,
  [2067] = 1,
    ACTIONS(572), 1,
      anon_sym_unsecure,
  [2071] = 1,
    ACTIONS(446), 1,
      sym_tag_close,
  [2075] = 1,
    ACTIONS(574), 1,
      anon_sym_each,
  [2079] = 1,
    ACTIONS(576), 1,
      anon_sym_unless,
  [2083] = 1,
    ACTIONS(578), 1,
      anon_sym_if,
  [2087] = 1,
    ACTIONS(580), 1,
      sym_identifier,
  [2091] = 1,
    ACTIONS(470), 1,
      sym_tag_close,
  [2095] = 1,
    ACTIONS(582), 1,
      sym_tag_close,
  [2099] = 1,
    ACTIONS(584), 1,
      sym__ws,
  [2103] = 1,
    ACTIONS(312), 1,
      sym_tag_close,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 52,
  [SMALL_STATE(4)] = 104,
  [SMALL_STATE(5)] = 150,
  [SMALL_STATE(6)] = 196,
  [SMALL_STATE(7)] = 242,
  [SMALL_STATE(8)] = 288,
  [SMALL_STATE(9)] = 334,
  [SMALL_STATE(10)] = 380,
  [SMALL_STATE(11)] = 426,
  [SMALL_STATE(12)] = 472,
  [SMALL_STATE(13)] = 515,
  [SMALL_STATE(14)] = 558,
  [SMALL_STATE(15)] = 578,
  [SMALL_STATE(16)] = 598,
  [SMALL_STATE(17)] = 610,
  [SMALL_STATE(18)] = 622,
  [SMALL_STATE(19)] = 634,
  [SMALL_STATE(20)] = 646,
  [SMALL_STATE(21)] = 658,
  [SMALL_STATE(22)] = 670,
  [SMALL_STATE(23)] = 682,
  [SMALL_STATE(24)] = 694,
  [SMALL_STATE(25)] = 706,
  [SMALL_STATE(26)] = 718,
  [SMALL_STATE(27)] = 730,
  [SMALL_STATE(28)] = 742,
  [SMALL_STATE(29)] = 754,
  [SMALL_STATE(30)] = 766,
  [SMALL_STATE(31)] = 778,
  [SMALL_STATE(32)] = 790,
  [SMALL_STATE(33)] = 802,
  [SMALL_STATE(34)] = 814,
  [SMALL_STATE(35)] = 826,
  [SMALL_STATE(36)] = 838,
  [SMALL_STATE(37)] = 850,
  [SMALL_STATE(38)] = 862,
  [SMALL_STATE(39)] = 874,
  [SMALL_STATE(40)] = 886,
  [SMALL_STATE(41)] = 898,
  [SMALL_STATE(42)] = 910,
  [SMALL_STATE(43)] = 922,
  [SMALL_STATE(44)] = 934,
  [SMALL_STATE(45)] = 946,
  [SMALL_STATE(46)] = 958,
  [SMALL_STATE(47)] = 970,
  [SMALL_STATE(48)] = 982,
  [SMALL_STATE(49)] = 993,
  [SMALL_STATE(50)] = 1004,
  [SMALL_STATE(51)] = 1015,
  [SMALL_STATE(52)] = 1026,
  [SMALL_STATE(53)] = 1037,
  [SMALL_STATE(54)] = 1056,
  [SMALL_STATE(55)] = 1067,
  [SMALL_STATE(56)] = 1078,
  [SMALL_STATE(57)] = 1089,
  [SMALL_STATE(58)] = 1102,
  [SMALL_STATE(59)] = 1121,
  [SMALL_STATE(60)] = 1132,
  [SMALL_STATE(61)] = 1143,
  [SMALL_STATE(62)] = 1154,
  [SMALL_STATE(63)] = 1173,
  [SMALL_STATE(64)] = 1192,
  [SMALL_STATE(65)] = 1211,
  [SMALL_STATE(66)] = 1222,
  [SMALL_STATE(67)] = 1233,
  [SMALL_STATE(68)] = 1244,
  [SMALL_STATE(69)] = 1255,
  [SMALL_STATE(70)] = 1268,
  [SMALL_STATE(71)] = 1281,
  [SMALL_STATE(72)] = 1292,
  [SMALL_STATE(73)] = 1306,
  [SMALL_STATE(74)] = 1320,
  [SMALL_STATE(75)] = 1328,
  [SMALL_STATE(76)] = 1344,
  [SMALL_STATE(77)] = 1360,
  [SMALL_STATE(78)] = 1376,
  [SMALL_STATE(79)] = 1389,
  [SMALL_STATE(80)] = 1402,
  [SMALL_STATE(81)] = 1415,
  [SMALL_STATE(82)] = 1428,
  [SMALL_STATE(83)] = 1441,
  [SMALL_STATE(84)] = 1451,
  [SMALL_STATE(85)] = 1461,
  [SMALL_STATE(86)] = 1471,
  [SMALL_STATE(87)] = 1481,
  [SMALL_STATE(88)] = 1491,
  [SMALL_STATE(89)] = 1501,
  [SMALL_STATE(90)] = 1511,
  [SMALL_STATE(91)] = 1518,
  [SMALL_STATE(92)] = 1525,
  [SMALL_STATE(93)] = 1532,
  [SMALL_STATE(94)] = 1539,
  [SMALL_STATE(95)] = 1546,
  [SMALL_STATE(96)] = 1553,
  [SMALL_STATE(97)] = 1558,
  [SMALL_STATE(98)] = 1565,
  [SMALL_STATE(99)] = 1572,
  [SMALL_STATE(100)] = 1577,
  [SMALL_STATE(101)] = 1584,
  [SMALL_STATE(102)] = 1591,
  [SMALL_STATE(103)] = 1598,
  [SMALL_STATE(104)] = 1605,
  [SMALL_STATE(105)] = 1612,
  [SMALL_STATE(106)] = 1619,
  [SMALL_STATE(107)] = 1626,
  [SMALL_STATE(108)] = 1633,
  [SMALL_STATE(109)] = 1640,
  [SMALL_STATE(110)] = 1645,
  [SMALL_STATE(111)] = 1652,
  [SMALL_STATE(112)] = 1659,
  [SMALL_STATE(113)] = 1664,
  [SMALL_STATE(114)] = 1671,
  [SMALL_STATE(115)] = 1678,
  [SMALL_STATE(116)] = 1683,
  [SMALL_STATE(117)] = 1690,
  [SMALL_STATE(118)] = 1697,
  [SMALL_STATE(119)] = 1704,
  [SMALL_STATE(120)] = 1711,
  [SMALL_STATE(121)] = 1718,
  [SMALL_STATE(122)] = 1725,
  [SMALL_STATE(123)] = 1732,
  [SMALL_STATE(124)] = 1739,
  [SMALL_STATE(125)] = 1746,
  [SMALL_STATE(126)] = 1753,
  [SMALL_STATE(127)] = 1758,
  [SMALL_STATE(128)] = 1765,
  [SMALL_STATE(129)] = 1772,
  [SMALL_STATE(130)] = 1779,
  [SMALL_STATE(131)] = 1786,
  [SMALL_STATE(132)] = 1793,
  [SMALL_STATE(133)] = 1800,
  [SMALL_STATE(134)] = 1807,
  [SMALL_STATE(135)] = 1814,
  [SMALL_STATE(136)] = 1819,
  [SMALL_STATE(137)] = 1826,
  [SMALL_STATE(138)] = 1833,
  [SMALL_STATE(139)] = 1840,
  [SMALL_STATE(140)] = 1847,
  [SMALL_STATE(141)] = 1854,
  [SMALL_STATE(142)] = 1859,
  [SMALL_STATE(143)] = 1866,
  [SMALL_STATE(144)] = 1873,
  [SMALL_STATE(145)] = 1880,
  [SMALL_STATE(146)] = 1887,
  [SMALL_STATE(147)] = 1891,
  [SMALL_STATE(148)] = 1895,
  [SMALL_STATE(149)] = 1899,
  [SMALL_STATE(150)] = 1903,
  [SMALL_STATE(151)] = 1907,
  [SMALL_STATE(152)] = 1911,
  [SMALL_STATE(153)] = 1915,
  [SMALL_STATE(154)] = 1919,
  [SMALL_STATE(155)] = 1923,
  [SMALL_STATE(156)] = 1927,
  [SMALL_STATE(157)] = 1931,
  [SMALL_STATE(158)] = 1935,
  [SMALL_STATE(159)] = 1939,
  [SMALL_STATE(160)] = 1943,
  [SMALL_STATE(161)] = 1947,
  [SMALL_STATE(162)] = 1951,
  [SMALL_STATE(163)] = 1955,
  [SMALL_STATE(164)] = 1959,
  [SMALL_STATE(165)] = 1963,
  [SMALL_STATE(166)] = 1967,
  [SMALL_STATE(167)] = 1971,
  [SMALL_STATE(168)] = 1975,
  [SMALL_STATE(169)] = 1979,
  [SMALL_STATE(170)] = 1983,
  [SMALL_STATE(171)] = 1987,
  [SMALL_STATE(172)] = 1991,
  [SMALL_STATE(173)] = 1995,
  [SMALL_STATE(174)] = 1999,
  [SMALL_STATE(175)] = 2003,
  [SMALL_STATE(176)] = 2007,
  [SMALL_STATE(177)] = 2011,
  [SMALL_STATE(178)] = 2015,
  [SMALL_STATE(179)] = 2019,
  [SMALL_STATE(180)] = 2023,
  [SMALL_STATE(181)] = 2027,
  [SMALL_STATE(182)] = 2031,
  [SMALL_STATE(183)] = 2035,
  [SMALL_STATE(184)] = 2039,
  [SMALL_STATE(185)] = 2043,
  [SMALL_STATE(186)] = 2047,
  [SMALL_STATE(187)] = 2051,
  [SMALL_STATE(188)] = 2055,
  [SMALL_STATE(189)] = 2059,
  [SMALL_STATE(190)] = 2063,
  [SMALL_STATE(191)] = 2067,
  [SMALL_STATE(192)] = 2071,
  [SMALL_STATE(193)] = 2075,
  [SMALL_STATE(194)] = 2079,
  [SMALL_STATE(195)] = 2083,
  [SMALL_STATE(196)] = 2087,
  [SMALL_STATE(197)] = 2091,
  [SMALL_STATE(198)] = 2095,
  [SMALL_STATE(199)] = 2099,
  [SMALL_STATE(200)] = 2103,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_else_clause, 1, 0, 0), SHIFT(77),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_else_clause, 2, 0, 0), SHIFT(77),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_block, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_block, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_close, 5, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_close, 5, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_block, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_block, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_output, 7, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_output, 7, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_close, 5, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_close, 5, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_block, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_block, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 9, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 9, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_close, 5, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_close, 5, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_block, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_block, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_close, 6, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_close, 6, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_close, 5, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_close, 5, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_block, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_block, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_close, 6, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_close, 6, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_close, 6, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_close, 6, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_close, 6, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_close, 6, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 7, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 7, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 6, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 6, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 6, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 6, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_output, 6, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_output, 6, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_close, 4, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_close, 4, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_close, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_close, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_close, 4, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_close, 4, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_close, 4, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_close, 4, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 8, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 8, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 5, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 5, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_block, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_block, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_output, 8, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_output, 8, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 4, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 4, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_block, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_block, 3, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_block, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_block, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_block, 4, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_block, 4, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_open, 4, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_open, 4, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_open, 5, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_open, 5, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_open, 13, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_open, 13, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_open, 12, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_open, 12, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_open, 11, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_open, 11, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(172),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(175),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(178),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_open, 10, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_open, 10, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_open, 8, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_open, 8, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_open, 8, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_open, 8, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(184),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_open, 6, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_open, 6, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_open, 7, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_open, 7, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_open, 7, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_open, 7, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_open, 5, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_open, 5, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_open, 6, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_open, 6, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_open, 4, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_open, 4, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_open, 6, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_open, 6, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [299] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(184),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_open, 6, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_open, 6, 0, 0),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(200),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(197),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(199),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [350] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_include_args_repeat1, 2, 0, 0),
  [352] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_include_args_repeat1, 2, 0, 0), SHIFT_REPEAT(142),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(162),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_args, 1, 0, 0),
  [365] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_include_args, 1, 0, 0), SHIFT(142),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(174),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(176),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(196),
  [382] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_index, 2, 0, 0),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(171),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(168),
  [392] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_arg, 5, 0, 0),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(192),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(163),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(189),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [410] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_arg, 4, 0, 0),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(164),
  [420] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_index, 4, 0, 0),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [428] = {.entry = {.count = 1, .reusable = true}}, SHIFT(180),
  [430] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_arg, 3, 0, 0),
  [432] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [436] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [438] = {.entry = {.count = 1, .reusable = true}}, SHIFT(195),
  [440] = {.entry = {.count = 1, .reusable = true}}, SHIFT(183),
  [442] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [444] = {.entry = {.count = 1, .reusable = true}}, SHIFT(194),
  [446] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [448] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [450] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [452] = {.entry = {.count = 1, .reusable = true}}, SHIFT(181),
  [454] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [456] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [458] = {.entry = {.count = 1, .reusable = true}}, SHIFT(198),
  [460] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [462] = {.entry = {.count = 1, .reusable = true}}, SHIFT(182),
  [464] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modifier, 1, 0, 0),
  [466] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [468] = {.entry = {.count = 1, .reusable = true}}, SHIFT(185),
  [470] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [472] = {.entry = {.count = 1, .reusable = true}}, SHIFT(186),
  [474] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [476] = {.entry = {.count = 1, .reusable = true}}, SHIFT(157),
  [478] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [480] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [482] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [484] = {.entry = {.count = 1, .reusable = true}}, SHIFT(193),
  [486] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [488] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [490] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_index, 3, 0, 0),
  [492] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [494] = {.entry = {.count = 1, .reusable = true}}, SHIFT(191),
  [496] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [498] = {.entry = {.count = 1, .reusable = true}}, SHIFT(166),
  [500] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [502] = {.entry = {.count = 1, .reusable = true}}, SHIFT(187),
  [504] = {.entry = {.count = 1, .reusable = true}}, SHIFT(169),
  [506] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [508] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [510] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [512] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [514] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [516] = {.entry = {.count = 1, .reusable = true}}, SHIFT(190),
  [518] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [520] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [522] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [524] = {.entry = {.count = 1, .reusable = true}}, SHIFT(170),
  [526] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [528] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [530] = {.entry = {.count = 1, .reusable = true}}, SHIFT(173),
  [532] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [534] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [536] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [538] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [540] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [542] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [544] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [546] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [548] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [550] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [552] = {.entry = {.count = 1, .reusable = true}}, SHIFT(179),
  [554] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [556] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [558] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [560] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [562] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [564] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [566] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [568] = {.entry = {.count = 1, .reusable = true}}, SHIFT(167),
  [570] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [572] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [574] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [576] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [578] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [580] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [582] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [584] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_natsuzora(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
