#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 181
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 13
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  aux_sym__text_char_token1 = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACK = 3,
  anon_sym_POUND = 4,
  anon_sym_if = 5,
  anon_sym_SLASH = 6,
  anon_sym_else = 7,
  anon_sym_unless = 8,
  anon_sym_each = 9,
  anon_sym_as = 10,
  anon_sym_COMMA = 11,
  anon_sym_unsecure = 12,
  anon_sym_GT = 13,
  anon_sym_EQ = 14,
  sym_comment = 15,
  sym_delimiter_escape = 16,
  sym_tag_open = 17,
  sym_tag_close = 18,
  anon_sym_DOT = 19,
  sym_identifier = 20,
  sym_include_name = 21,
  sym__ws = 22,
  sym_template = 23,
  sym__node = 24,
  sym_text = 25,
  sym__text_char = 26,
  sym_variable = 27,
  sym_if_block = 28,
  sym_if_open = 29,
  sym_if_close = 30,
  sym_else_clause = 31,
  sym_else_open = 32,
  sym_unless_block = 33,
  sym_unless_open = 34,
  sym_unless_close = 35,
  sym_each_block = 36,
  sym_each_open = 37,
  sym_each_index = 38,
  sym_each_close = 39,
  sym_unsecure_block = 40,
  sym_unsecure_open = 41,
  sym_unsecure_close = 42,
  sym_include = 43,
  sym_include_args = 44,
  sym_include_arg = 45,
  sym_path = 46,
  aux_sym_template_repeat1 = 47,
  aux_sym_text_repeat1 = 48,
  aux_sym_include_args_repeat1 = 49,
  aux_sym_path_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__text_char_token1] = "_text_char_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACK] = "]",
  [anon_sym_POUND] = "#",
  [anon_sym_if] = "if",
  [anon_sym_SLASH] = "/",
  [anon_sym_else] = "else",
  [anon_sym_unless] = "unless",
  [anon_sym_each] = "each",
  [anon_sym_as] = "as",
  [anon_sym_COMMA] = ",",
  [anon_sym_unsecure] = "unsecure",
  [anon_sym_GT] = ">",
  [anon_sym_EQ] = "=",
  [sym_comment] = "comment",
  [sym_delimiter_escape] = "delimiter_escape",
  [sym_tag_open] = "tag_open",
  [sym_tag_close] = "tag_close",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [sym_include_name] = "include_name",
  [sym__ws] = "_ws",
  [sym_template] = "template",
  [sym__node] = "_node",
  [sym_text] = "text",
  [sym__text_char] = "_text_char",
  [sym_variable] = "variable",
  [sym_if_block] = "if_block",
  [sym_if_open] = "if_open",
  [sym_if_close] = "if_close",
  [sym_else_clause] = "else_clause",
  [sym_else_open] = "else_open",
  [sym_unless_block] = "unless_block",
  [sym_unless_open] = "unless_open",
  [sym_unless_close] = "unless_close",
  [sym_each_block] = "each_block",
  [sym_each_open] = "each_open",
  [sym_each_index] = "each_index",
  [sym_each_close] = "each_close",
  [sym_unsecure_block] = "unsecure_block",
  [sym_unsecure_open] = "unsecure_open",
  [sym_unsecure_close] = "unsecure_close",
  [sym_include] = "include",
  [sym_include_args] = "include_args",
  [sym_include_arg] = "include_arg",
  [sym_path] = "path",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_text_repeat1] = "text_repeat1",
  [aux_sym_include_args_repeat1] = "include_args_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__text_char_token1] = aux_sym__text_char_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_unless] = anon_sym_unless,
  [anon_sym_each] = anon_sym_each,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_unsecure] = anon_sym_unsecure,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_comment] = sym_comment,
  [sym_delimiter_escape] = sym_delimiter_escape,
  [sym_tag_open] = sym_tag_open,
  [sym_tag_close] = sym_tag_close,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [sym_include_name] = sym_include_name,
  [sym__ws] = sym__ws,
  [sym_template] = sym_template,
  [sym__node] = sym__node,
  [sym_text] = sym_text,
  [sym__text_char] = sym__text_char,
  [sym_variable] = sym_variable,
  [sym_if_block] = sym_if_block,
  [sym_if_open] = sym_if_open,
  [sym_if_close] = sym_if_close,
  [sym_else_clause] = sym_else_clause,
  [sym_else_open] = sym_else_open,
  [sym_unless_block] = sym_unless_block,
  [sym_unless_open] = sym_unless_open,
  [sym_unless_close] = sym_unless_close,
  [sym_each_block] = sym_each_block,
  [sym_each_open] = sym_each_open,
  [sym_each_index] = sym_each_index,
  [sym_each_close] = sym_each_close,
  [sym_unsecure_block] = sym_unsecure_block,
  [sym_unsecure_open] = sym_unsecure_open,
  [sym_unsecure_close] = sym_unsecure_close,
  [sym_include] = sym_include,
  [sym_include_args] = sym_include_args,
  [sym_include_arg] = sym_include_arg,
  [sym_path] = sym_path,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
  [aux_sym_include_args_repeat1] = aux_sym_include_args_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__text_char_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_each] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unsecure] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_open] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_close] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_include_name] = {
    .visible = true,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__text_char] = {
    .visible = false,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_if_block] = {
    .visible = true,
    .named = true,
  },
  [sym_if_open] = {
    .visible = true,
    .named = true,
  },
  [sym_if_close] = {
    .visible = true,
    .named = true,
  },
  [sym_else_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_else_open] = {
    .visible = true,
    .named = true,
  },
  [sym_unless_block] = {
    .visible = true,
    .named = true,
  },
  [sym_unless_open] = {
    .visible = true,
    .named = true,
  },
  [sym_unless_close] = {
    .visible = true,
    .named = true,
  },
  [sym_each_block] = {
    .visible = true,
    .named = true,
  },
  [sym_each_open] = {
    .visible = true,
    .named = true,
  },
  [sym_each_index] = {
    .visible = true,
    .named = true,
  },
  [sym_each_close] = {
    .visible = true,
    .named = true,
  },
  [sym_unsecure_block] = {
    .visible = true,
    .named = true,
  },
  [sym_unsecure_open] = {
    .visible = true,
    .named = true,
  },
  [sym_unsecure_close] = {
    .visible = true,
    .named = true,
  },
  [sym_include] = {
    .visible = true,
    .named = true,
  },
  [sym_include_args] = {
    .visible = true,
    .named = true,
  },
  [sym_include_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_include_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
  [156] = 156,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 160,
  [161] = 161,
  [162] = 162,
  [163] = 163,
  [164] = 164,
  [165] = 165,
  [166] = 166,
  [167] = 167,
  [168] = 168,
  [169] = 169,
  [170] = 170,
  [171] = 171,
  [172] = 172,
  [173] = 173,
  [174] = 174,
  [175] = 175,
  [176] = 176,
  [177] = 177,
  [178] = 178,
  [179] = 179,
  [180] = 180,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '#', 33,
        ',', 45,
        '.', 55,
        '/', 36,
        '=', 49,
        '>', 48,
        ']', 32,
        'a', 68,
        'e', 56,
        'i', 63,
        'u', 66,
        '{', 31,
        '\t', 75,
        '\n', 75,
        '\r', 75,
        ' ', 75,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '#', 33,
        ',', 45,
        '-', 6,
        '.', 55,
        '/', 36,
        '>', 48,
        ']', 26,
        '\t', 75,
        '\n', 75,
        '\r', 75,
        ' ', 75,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == ']') ADVANCE(24);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '/', 27,
        'a', 19,
        'e', 7,
        'i', 14,
        'u', 17,
        '\t', 75,
        '\n', 75,
        '\r', 75,
        ' ', 75,
      );
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(24);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == ']') ADVANCE(26);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(34);
      END_STATE();
    case 15:
      if (lookahead == 'h') ADVANCE(41);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(13);
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(43);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 24:
      if (lookahead == '}') ADVANCE(50);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 25:
      if (lookahead == '}') ADVANCE(51);
      END_STATE();
    case 26:
      if (lookahead == '}') ADVANCE(54);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == '{') ADVANCE(31);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__text_char_token1);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '{') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '[') ADVANCE(53);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_unless);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_unless);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_each);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_each);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_as);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_unsecure);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_unsecure);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_delimiter_escape);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_tag_open);
      if (lookahead == '!') ADVANCE(2);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_tag_open);
      if (lookahead == '!') ADVANCE(2);
      if (lookahead == '-') ADVANCE(52);
      if (lookahead == '{') ADVANCE(5);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_tag_close);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(57);
      if (lookahead == 'l') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(62);
      if (lookahead == 's') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_include_name);
      if (lookahead == '/') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(75);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 28},
  [3] = {.lex_state = 28},
  [4] = {.lex_state = 28},
  [5] = {.lex_state = 28},
  [6] = {.lex_state = 28},
  [7] = {.lex_state = 28},
  [8] = {.lex_state = 28},
  [9] = {.lex_state = 28},
  [10] = {.lex_state = 28},
  [11] = {.lex_state = 28},
  [12] = {.lex_state = 28},
  [13] = {.lex_state = 28},
  [14] = {.lex_state = 28},
  [15] = {.lex_state = 28},
  [16] = {.lex_state = 28},
  [17] = {.lex_state = 28},
  [18] = {.lex_state = 28},
  [19] = {.lex_state = 28},
  [20] = {.lex_state = 28},
  [21] = {.lex_state = 28},
  [22] = {.lex_state = 28},
  [23] = {.lex_state = 28},
  [24] = {.lex_state = 28},
  [25] = {.lex_state = 28},
  [26] = {.lex_state = 28},
  [27] = {.lex_state = 28},
  [28] = {.lex_state = 28},
  [29] = {.lex_state = 28},
  [30] = {.lex_state = 28},
  [31] = {.lex_state = 28},
  [32] = {.lex_state = 28},
  [33] = {.lex_state = 28},
  [34] = {.lex_state = 28},
  [35] = {.lex_state = 28},
  [36] = {.lex_state = 28},
  [37] = {.lex_state = 28},
  [38] = {.lex_state = 28},
  [39] = {.lex_state = 28},
  [40] = {.lex_state = 28},
  [41] = {.lex_state = 28},
  [42] = {.lex_state = 28},
  [43] = {.lex_state = 28},
  [44] = {.lex_state = 28},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 28},
  [47] = {.lex_state = 28},
  [48] = {.lex_state = 28},
  [49] = {.lex_state = 28},
  [50] = {.lex_state = 28},
  [51] = {.lex_state = 28},
  [52] = {.lex_state = 28},
  [53] = {.lex_state = 28},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 28},
  [56] = {.lex_state = 28},
  [57] = {.lex_state = 28},
  [58] = {.lex_state = 28},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 28},
  [62] = {.lex_state = 28},
  [63] = {.lex_state = 28},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 3},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 1},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 1},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 1},
  [109] = {.lex_state = 1},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 1},
  [115] = {.lex_state = 1},
  [116] = {.lex_state = 1},
  [117] = {.lex_state = 1},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 1},
  [120] = {.lex_state = 1},
  [121] = {.lex_state = 1},
  [122] = {.lex_state = 1},
  [123] = {.lex_state = 1},
  [124] = {.lex_state = 3},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 1},
  [127] = {.lex_state = 1},
  [128] = {.lex_state = 3},
  [129] = {.lex_state = 3},
  [130] = {.lex_state = 3},
  [131] = {.lex_state = 1},
  [132] = {.lex_state = 1},
  [133] = {.lex_state = 1},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 1},
  [137] = {.lex_state = 1},
  [138] = {.lex_state = 1},
  [139] = {.lex_state = 1},
  [140] = {.lex_state = 1},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 1},
  [143] = {.lex_state = 1},
  [144] = {.lex_state = 3},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 1},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 1},
  [153] = {.lex_state = 3},
  [154] = {.lex_state = 1},
  [155] = {.lex_state = 3},
  [156] = {.lex_state = 1},
  [157] = {.lex_state = 1},
  [158] = {.lex_state = 1},
  [159] = {.lex_state = 1},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 1},
  [162] = {.lex_state = 1},
  [163] = {.lex_state = 1},
  [164] = {.lex_state = 0},
  [165] = {.lex_state = 1},
  [166] = {.lex_state = 1},
  [167] = {.lex_state = 1},
  [168] = {.lex_state = 3},
  [169] = {.lex_state = 1},
  [170] = {.lex_state = 1},
  [171] = {.lex_state = 3},
  [172] = {.lex_state = 1},
  [173] = {.lex_state = 3},
  [174] = {.lex_state = 1},
  [175] = {.lex_state = 0},
  [176] = {.lex_state = 1},
  [177] = {.lex_state = 1},
  [178] = {.lex_state = 1},
  [179] = {.lex_state = 0},
  [180] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_unless] = ACTIONS(1),
    [anon_sym_each] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_unsecure] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_delimiter_escape] = ACTIONS(1),
    [sym_tag_open] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
  },
  [1] = {
    [sym_template] = STATE(175),
    [sym__node] = STATE(7),
    [sym_text] = STATE(7),
    [sym__text_char] = STATE(15),
    [sym_variable] = STATE(7),
    [sym_if_block] = STATE(7),
    [sym_if_open] = STATE(2),
    [sym_unless_block] = STATE(7),
    [sym_unless_open] = STATE(4),
    [sym_each_block] = STATE(7),
    [sym_each_open] = STATE(5),
    [sym_unsecure_block] = STATE(7),
    [sym_unsecure_open] = STATE(6),
    [sym_include] = STATE(7),
    [aux_sym_template_repeat1] = STATE(7),
    [aux_sym_text_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym__text_char_token1] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACK] = ACTIONS(5),
    [sym_comment] = ACTIONS(9),
    [sym_delimiter_escape] = ACTIONS(9),
    [sym_tag_open] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(13), 1,
      sym_else_open,
    STATE(23), 1,
      sym_if_close,
    STATE(105), 1,
      sym_else_clause,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(13), 2,
      sym_comment,
      sym_delimiter_escape,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(3), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_include,
      aux_sym_template_repeat1,
  [51] = 13,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(13), 1,
      sym_else_open,
    STATE(43), 1,
      sym_if_close,
    STATE(125), 1,
      sym_else_clause,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_comment,
      sym_delimiter_escape,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(10), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_include,
      aux_sym_template_repeat1,
  [102] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(26), 1,
      sym_unless_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(19), 2,
      sym_comment,
      sym_delimiter_escape,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(11), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_include,
      aux_sym_template_repeat1,
  [147] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(28), 1,
      sym_each_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(23), 2,
      sym_comment,
      sym_delimiter_escape,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(9), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_include,
      aux_sym_template_repeat1,
  [192] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(30), 1,
      sym_unsecure_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(27), 2,
      sym_comment,
      sym_delimiter_escape,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(8), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_include,
      aux_sym_template_repeat1,
  [237] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_tag_open,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_comment,
      sym_delimiter_escape,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(10), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_include,
      aux_sym_template_repeat1,
  [282] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(35), 1,
      sym_unsecure_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_comment,
      sym_delimiter_escape,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(10), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_include,
      aux_sym_template_repeat1,
  [327] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(39), 1,
      sym_each_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_comment,
      sym_delimiter_escape,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(10), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_include,
      aux_sym_template_repeat1,
  [372] = 11,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(44), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    ACTIONS(35), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(41), 2,
      sym_comment,
      sym_delimiter_escape,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(10), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_include,
      aux_sym_template_repeat1,
  [417] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    STATE(42), 1,
      sym_unless_close,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_comment,
      sym_delimiter_escape,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(10), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_include,
      aux_sym_template_repeat1,
  [462] = 10,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(17), 2,
      sym_comment,
      sym_delimiter_escape,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(10), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_include,
      aux_sym_template_repeat1,
  [504] = 10,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      sym_tag_open,
    STATE(2), 1,
      sym_if_open,
    STATE(4), 1,
      sym_unless_open,
    STATE(5), 1,
      sym_each_open,
    STATE(6), 1,
      sym_unsecure_open,
    ACTIONS(5), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    ACTIONS(50), 2,
      sym_comment,
      sym_delimiter_escape,
    STATE(15), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    STATE(12), 9,
      sym__node,
      sym_text,
      sym_variable,
      sym_if_block,
      sym_unless_block,
      sym_each_block,
      sym_unsecure_block,
      sym_include,
      aux_sym_template_repeat1,
  [546] = 5,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_tag_open,
    ACTIONS(57), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_delimiter_escape,
  [566] = 5,
    ACTIONS(69), 1,
      anon_sym_LBRACE,
    ACTIONS(71), 1,
      sym_tag_open,
    ACTIONS(67), 2,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
    STATE(14), 2,
      sym__text_char,
      aux_sym_text_repeat1,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_delimiter_escape,
  [586] = 2,
    ACTIONS(75), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(73), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [598] = 2,
    ACTIONS(79), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [610] = 2,
    ACTIONS(83), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(81), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [622] = 2,
    ACTIONS(87), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(85), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [634] = 2,
    ACTIONS(91), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(89), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [646] = 2,
    ACTIONS(95), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(93), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [658] = 2,
    ACTIONS(99), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(97), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [670] = 2,
    ACTIONS(103), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(101), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [682] = 2,
    ACTIONS(107), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(105), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [694] = 2,
    ACTIONS(111), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [706] = 2,
    ACTIONS(115), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(113), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [718] = 2,
    ACTIONS(119), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(117), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [730] = 2,
    ACTIONS(123), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(121), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [742] = 2,
    ACTIONS(127), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(125), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [754] = 2,
    ACTIONS(131), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(129), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [766] = 2,
    ACTIONS(135), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [778] = 2,
    ACTIONS(139), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(137), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [790] = 2,
    ACTIONS(143), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [802] = 2,
    ACTIONS(147), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(145), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [814] = 2,
    ACTIONS(151), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(149), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [826] = 2,
    ACTIONS(155), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(153), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [838] = 2,
    ACTIONS(159), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(157), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [850] = 2,
    ACTIONS(163), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(161), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [862] = 2,
    ACTIONS(167), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(165), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [874] = 2,
    ACTIONS(171), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(169), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [886] = 2,
    ACTIONS(175), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(173), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [898] = 2,
    ACTIONS(179), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(177), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [910] = 2,
    ACTIONS(183), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(181), 5,
      ts_builtin_sym_end,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [922] = 2,
    ACTIONS(187), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(185), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [933] = 6,
    ACTIONS(189), 1,
      anon_sym_POUND,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    ACTIONS(193), 1,
      anon_sym_GT,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym__ws,
    STATE(100), 1,
      sym_path,
  [952] = 2,
    ACTIONS(201), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(199), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [963] = 2,
    ACTIONS(205), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(203), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [974] = 2,
    ACTIONS(209), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(207), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [985] = 2,
    ACTIONS(213), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(211), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [996] = 2,
    ACTIONS(217), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(215), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [1007] = 2,
    ACTIONS(221), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(219), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [1018] = 2,
    ACTIONS(225), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(223), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [1029] = 2,
    ACTIONS(229), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(227), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [1040] = 6,
    ACTIONS(193), 1,
      anon_sym_GT,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym__ws,
    ACTIONS(231), 1,
      anon_sym_POUND,
    ACTIONS(233), 1,
      anon_sym_SLASH,
    STATE(100), 1,
      sym_path,
  [1059] = 2,
    ACTIONS(237), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(235), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [1070] = 2,
    ACTIONS(241), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(239), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [1081] = 2,
    ACTIONS(245), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(243), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [1092] = 2,
    ACTIONS(249), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(247), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [1103] = 6,
    ACTIONS(251), 1,
      anon_sym_if,
    ACTIONS(253), 1,
      anon_sym_else,
    ACTIONS(255), 1,
      anon_sym_unless,
    ACTIONS(257), 1,
      anon_sym_each,
    ACTIONS(259), 1,
      anon_sym_unsecure,
    ACTIONS(261), 1,
      sym__ws,
  [1122] = 6,
    ACTIONS(189), 1,
      anon_sym_POUND,
    ACTIONS(193), 1,
      anon_sym_GT,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym__ws,
    ACTIONS(263), 1,
      anon_sym_SLASH,
    STATE(100), 1,
      sym_path,
  [1141] = 2,
    ACTIONS(267), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(265), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [1152] = 2,
    ACTIONS(271), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(269), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [1163] = 2,
    ACTIONS(275), 2,
      anon_sym_LBRACE,
      sym_tag_open,
    ACTIONS(273), 4,
      aux_sym__text_char_token1,
      anon_sym_RBRACK,
      sym_comment,
      sym_delimiter_escape,
  [1174] = 6,
    ACTIONS(189), 1,
      anon_sym_POUND,
    ACTIONS(193), 1,
      anon_sym_GT,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym__ws,
    ACTIONS(277), 1,
      anon_sym_SLASH,
    STATE(100), 1,
      sym_path,
  [1193] = 5,
    ACTIONS(251), 1,
      anon_sym_if,
    ACTIONS(255), 1,
      anon_sym_unless,
    ACTIONS(257), 1,
      anon_sym_each,
    ACTIONS(259), 1,
      anon_sym_unsecure,
    ACTIONS(279), 1,
      sym__ws,
  [1209] = 5,
    ACTIONS(281), 1,
      anon_sym_if,
    ACTIONS(283), 1,
      anon_sym_else,
    ACTIONS(285), 1,
      anon_sym_unless,
    ACTIONS(287), 1,
      anon_sym_each,
    ACTIONS(289), 1,
      anon_sym_unsecure,
  [1225] = 5,
    ACTIONS(189), 1,
      anon_sym_POUND,
    ACTIONS(193), 1,
      anon_sym_GT,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym__ws,
    STATE(100), 1,
      sym_path,
  [1241] = 4,
    ACTIONS(291), 1,
      anon_sym_COMMA,
    ACTIONS(293), 1,
      sym_tag_close,
    ACTIONS(295), 1,
      sym__ws,
    STATE(108), 1,
      sym_each_index,
  [1254] = 4,
    ACTIONS(297), 1,
      sym_tag_close,
    ACTIONS(299), 1,
      sym__ws,
    STATE(77), 1,
      aux_sym_include_args_repeat1,
    STATE(99), 1,
      sym_include_args,
  [1267] = 3,
    ACTIONS(303), 1,
      anon_sym_DOT,
    STATE(70), 1,
      aux_sym_path_repeat1,
    ACTIONS(301), 2,
      sym_tag_close,
      sym__ws,
  [1278] = 4,
    ACTIONS(281), 1,
      anon_sym_if,
    ACTIONS(285), 1,
      anon_sym_unless,
    ACTIONS(287), 1,
      anon_sym_each,
    ACTIONS(289), 1,
      anon_sym_unsecure,
  [1291] = 4,
    ACTIONS(306), 1,
      sym_tag_close,
    ACTIONS(308), 1,
      sym__ws,
    STATE(77), 1,
      aux_sym_include_args_repeat1,
    STATE(116), 1,
      sym_include_args,
  [1304] = 3,
    ACTIONS(312), 1,
      anon_sym_DOT,
    STATE(70), 1,
      aux_sym_path_repeat1,
    ACTIONS(310), 2,
      sym_tag_close,
      sym__ws,
  [1315] = 4,
    ACTIONS(291), 1,
      anon_sym_COMMA,
    ACTIONS(314), 1,
      sym_tag_close,
    ACTIONS(316), 1,
      sym__ws,
    STATE(95), 1,
      sym_each_index,
  [1328] = 3,
    ACTIONS(312), 1,
      anon_sym_DOT,
    STATE(73), 1,
      aux_sym_path_repeat1,
    ACTIONS(318), 2,
      sym_tag_close,
      sym__ws,
  [1339] = 3,
    ACTIONS(297), 1,
      sym_tag_close,
    ACTIONS(320), 1,
      sym_identifier,
    STATE(94), 1,
      sym_include_arg,
  [1349] = 3,
    ACTIONS(322), 1,
      sym_tag_close,
    ACTIONS(324), 1,
      sym__ws,
    STATE(81), 1,
      aux_sym_include_args_repeat1,
  [1359] = 1,
    ACTIONS(301), 3,
      sym_tag_close,
      anon_sym_DOT,
      sym__ws,
  [1365] = 3,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(327), 1,
      sym__ws,
    STATE(126), 1,
      sym_path,
  [1375] = 3,
    ACTIONS(320), 1,
      sym_identifier,
    ACTIONS(329), 1,
      sym_tag_close,
    STATE(94), 1,
      sym_include_arg,
  [1385] = 3,
    ACTIONS(331), 1,
      sym_tag_close,
    ACTIONS(333), 1,
      sym__ws,
    STATE(81), 1,
      aux_sym_include_args_repeat1,
  [1395] = 3,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(336), 1,
      sym__ws,
    STATE(119), 1,
      sym_path,
  [1405] = 2,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(151), 1,
      sym_path,
  [1412] = 2,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(87), 1,
      sym_path,
  [1419] = 2,
    ACTIONS(338), 1,
      sym_include_name,
    ACTIONS(340), 1,
      sym__ws,
  [1426] = 2,
    ACTIONS(342), 1,
      sym_tag_close,
    ACTIONS(344), 1,
      sym__ws,
  [1433] = 2,
    ACTIONS(346), 1,
      sym_tag_close,
    ACTIONS(348), 1,
      sym__ws,
  [1440] = 1,
    ACTIONS(350), 2,
      sym_tag_close,
      sym__ws,
  [1445] = 2,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(121), 1,
      sym_path,
  [1452] = 2,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(122), 1,
      sym_path,
  [1459] = 2,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(123), 1,
      sym_path,
  [1466] = 1,
    ACTIONS(352), 2,
      sym_tag_close,
      sym__ws,
  [1471] = 2,
    ACTIONS(354), 1,
      anon_sym_EQ,
    ACTIONS(356), 1,
      sym__ws,
  [1478] = 1,
    ACTIONS(331), 2,
      sym_tag_close,
      sym__ws,
  [1483] = 2,
    ACTIONS(358), 1,
      sym_tag_close,
    ACTIONS(360), 1,
      sym__ws,
  [1490] = 2,
    ACTIONS(320), 1,
      sym_identifier,
    STATE(94), 1,
      sym_include_arg,
  [1497] = 2,
    ACTIONS(358), 1,
      sym_tag_close,
    ACTIONS(362), 1,
      anon_sym_COMMA,
  [1504] = 2,
    ACTIONS(364), 1,
      sym_tag_close,
    ACTIONS(366), 1,
      sym__ws,
  [1511] = 2,
    ACTIONS(329), 1,
      sym_tag_close,
    ACTIONS(368), 1,
      sym__ws,
  [1518] = 2,
    ACTIONS(370), 1,
      sym_tag_close,
    ACTIONS(372), 1,
      sym__ws,
  [1525] = 2,
    ACTIONS(374), 1,
      sym_tag_close,
    ACTIONS(376), 1,
      sym__ws,
  [1532] = 2,
    ACTIONS(378), 1,
      sym_identifier,
    ACTIONS(380), 1,
      sym__ws,
  [1539] = 2,
    ACTIONS(382), 1,
      sym_tag_close,
    ACTIONS(384), 1,
      sym__ws,
  [1546] = 1,
    ACTIONS(386), 2,
      sym_tag_close,
      sym__ws,
  [1551] = 2,
    ACTIONS(388), 1,
      sym_tag_open,
    STATE(43), 1,
      sym_if_close,
  [1558] = 2,
    ACTIONS(390), 1,
      sym_tag_close,
    ACTIONS(392), 1,
      sym__ws,
  [1565] = 2,
    ACTIONS(394), 1,
      sym_tag_close,
    ACTIONS(396), 1,
      sym__ws,
  [1572] = 2,
    ACTIONS(314), 1,
      sym_tag_close,
    ACTIONS(398), 1,
      sym__ws,
  [1579] = 2,
    ACTIONS(400), 1,
      sym_tag_close,
    ACTIONS(402), 1,
      sym__ws,
  [1586] = 2,
    ACTIONS(404), 1,
      sym_tag_close,
    ACTIONS(406), 1,
      sym__ws,
  [1593] = 2,
    ACTIONS(314), 1,
      sym_tag_close,
    ACTIONS(362), 1,
      anon_sym_COMMA,
  [1600] = 2,
    ACTIONS(408), 1,
      sym_tag_close,
    ACTIONS(410), 1,
      sym__ws,
  [1607] = 2,
    ACTIONS(412), 1,
      sym_identifier,
    ACTIONS(414), 1,
      sym__ws,
  [1614] = 1,
    ACTIONS(416), 2,
      sym_tag_close,
      sym__ws,
  [1619] = 2,
    ACTIONS(418), 1,
      sym_tag_close,
    ACTIONS(420), 1,
      sym__ws,
  [1626] = 2,
    ACTIONS(297), 1,
      sym_tag_close,
    ACTIONS(422), 1,
      sym__ws,
  [1633] = 2,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(114), 1,
      sym_path,
  [1640] = 2,
    ACTIONS(424), 1,
      sym_tag_close,
    ACTIONS(426), 1,
      sym__ws,
  [1647] = 1,
    ACTIONS(428), 2,
      sym_tag_close,
      sym__ws,
  [1652] = 2,
    ACTIONS(430), 1,
      sym_tag_close,
    ACTIONS(432), 1,
      sym__ws,
  [1659] = 2,
    ACTIONS(434), 1,
      sym_tag_close,
    ACTIONS(436), 1,
      sym__ws,
  [1666] = 2,
    ACTIONS(438), 1,
      sym_tag_close,
    ACTIONS(440), 1,
      sym__ws,
  [1673] = 2,
    ACTIONS(442), 1,
      sym_tag_close,
    ACTIONS(444), 1,
      sym__ws,
  [1680] = 2,
    ACTIONS(446), 1,
      anon_sym_if,
    ACTIONS(448), 1,
      sym__ws,
  [1687] = 2,
    ACTIONS(388), 1,
      sym_tag_open,
    STATE(20), 1,
      sym_if_close,
  [1694] = 1,
    ACTIONS(450), 2,
      sym_tag_close,
      sym__ws,
  [1699] = 2,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(119), 1,
      sym_path,
  [1706] = 2,
    ACTIONS(452), 1,
      anon_sym_unless,
    ACTIONS(454), 1,
      sym__ws,
  [1713] = 2,
    ACTIONS(456), 1,
      anon_sym_each,
    ACTIONS(458), 1,
      sym__ws,
  [1720] = 2,
    ACTIONS(460), 1,
      anon_sym_unsecure,
    ACTIONS(462), 1,
      sym__ws,
  [1727] = 2,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(179), 1,
      sym_path,
  [1734] = 2,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(86), 1,
      sym_path,
  [1741] = 2,
    ACTIONS(464), 1,
      sym_tag_close,
    ACTIONS(466), 1,
      sym__ws,
  [1748] = 1,
    ACTIONS(468), 1,
      sym__ws,
  [1752] = 1,
    ACTIONS(470), 1,
      anon_sym_EQ,
  [1756] = 1,
    ACTIONS(472), 1,
      sym_tag_close,
  [1760] = 1,
    ACTIONS(474), 1,
      sym_tag_close,
  [1764] = 1,
    ACTIONS(476), 1,
      sym_tag_close,
  [1768] = 1,
    ACTIONS(424), 1,
      sym_tag_close,
  [1772] = 1,
    ACTIONS(478), 1,
      sym_tag_close,
  [1776] = 1,
    ACTIONS(480), 1,
      sym__ws,
  [1780] = 1,
    ACTIONS(482), 1,
      sym_tag_close,
  [1784] = 1,
    ACTIONS(484), 1,
      sym_tag_close,
  [1788] = 1,
    ACTIONS(486), 1,
      anon_sym_as,
  [1792] = 1,
    ACTIONS(488), 1,
      sym__ws,
  [1796] = 1,
    ACTIONS(490), 1,
      sym__ws,
  [1800] = 1,
    ACTIONS(492), 1,
      sym__ws,
  [1804] = 1,
    ACTIONS(233), 1,
      anon_sym_SLASH,
  [1808] = 1,
    ACTIONS(494), 1,
      sym__ws,
  [1812] = 1,
    ACTIONS(442), 1,
      sym_tag_close,
  [1816] = 1,
    ACTIONS(496), 1,
      sym__ws,
  [1820] = 1,
    ACTIONS(498), 1,
      sym_identifier,
  [1824] = 1,
    ACTIONS(500), 1,
      sym_include_name,
  [1828] = 1,
    ACTIONS(502), 1,
      sym_identifier,
  [1832] = 1,
    ACTIONS(504), 1,
      anon_sym_as,
  [1836] = 1,
    ACTIONS(506), 1,
      sym_tag_close,
  [1840] = 1,
    ACTIONS(508), 1,
      sym_tag_close,
  [1844] = 1,
    ACTIONS(408), 1,
      sym_tag_close,
  [1848] = 1,
    ACTIONS(434), 1,
      sym_tag_close,
  [1852] = 1,
    ACTIONS(510), 1,
      sym__ws,
  [1856] = 1,
    ACTIONS(512), 1,
      sym_identifier,
  [1860] = 1,
    ACTIONS(418), 1,
      sym_tag_close,
  [1864] = 1,
    ACTIONS(514), 1,
      sym_tag_close,
  [1868] = 1,
    ACTIONS(516), 1,
      sym__ws,
  [1872] = 1,
    ACTIONS(438), 1,
      sym_tag_close,
  [1876] = 1,
    ACTIONS(400), 1,
      sym_tag_close,
  [1880] = 1,
    ACTIONS(390), 1,
      sym_tag_close,
  [1884] = 1,
    ACTIONS(518), 1,
      anon_sym_if,
  [1888] = 1,
    ACTIONS(378), 1,
      sym_identifier,
  [1892] = 1,
    ACTIONS(382), 1,
      sym_tag_close,
  [1896] = 1,
    ACTIONS(520), 1,
      anon_sym_unless,
  [1900] = 1,
    ACTIONS(358), 1,
      sym_tag_close,
  [1904] = 1,
    ACTIONS(522), 1,
      anon_sym_each,
  [1908] = 1,
    ACTIONS(329), 1,
      sym_tag_close,
  [1912] = 1,
    ACTIONS(524), 1,
      ts_builtin_sym_end,
  [1916] = 1,
    ACTIONS(526), 1,
      sym_identifier,
  [1920] = 1,
    ACTIONS(528), 1,
      sym_tag_close,
  [1924] = 1,
    ACTIONS(530), 1,
      sym_tag_close,
  [1928] = 1,
    ACTIONS(532), 1,
      sym__ws,
  [1932] = 1,
    ACTIONS(534), 1,
      anon_sym_unsecure,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 51,
  [SMALL_STATE(4)] = 102,
  [SMALL_STATE(5)] = 147,
  [SMALL_STATE(6)] = 192,
  [SMALL_STATE(7)] = 237,
  [SMALL_STATE(8)] = 282,
  [SMALL_STATE(9)] = 327,
  [SMALL_STATE(10)] = 372,
  [SMALL_STATE(11)] = 417,
  [SMALL_STATE(12)] = 462,
  [SMALL_STATE(13)] = 504,
  [SMALL_STATE(14)] = 546,
  [SMALL_STATE(15)] = 566,
  [SMALL_STATE(16)] = 586,
  [SMALL_STATE(17)] = 598,
  [SMALL_STATE(18)] = 610,
  [SMALL_STATE(19)] = 622,
  [SMALL_STATE(20)] = 634,
  [SMALL_STATE(21)] = 646,
  [SMALL_STATE(22)] = 658,
  [SMALL_STATE(23)] = 670,
  [SMALL_STATE(24)] = 682,
  [SMALL_STATE(25)] = 694,
  [SMALL_STATE(26)] = 706,
  [SMALL_STATE(27)] = 718,
  [SMALL_STATE(28)] = 730,
  [SMALL_STATE(29)] = 742,
  [SMALL_STATE(30)] = 754,
  [SMALL_STATE(31)] = 766,
  [SMALL_STATE(32)] = 778,
  [SMALL_STATE(33)] = 790,
  [SMALL_STATE(34)] = 802,
  [SMALL_STATE(35)] = 814,
  [SMALL_STATE(36)] = 826,
  [SMALL_STATE(37)] = 838,
  [SMALL_STATE(38)] = 850,
  [SMALL_STATE(39)] = 862,
  [SMALL_STATE(40)] = 874,
  [SMALL_STATE(41)] = 886,
  [SMALL_STATE(42)] = 898,
  [SMALL_STATE(43)] = 910,
  [SMALL_STATE(44)] = 922,
  [SMALL_STATE(45)] = 933,
  [SMALL_STATE(46)] = 952,
  [SMALL_STATE(47)] = 963,
  [SMALL_STATE(48)] = 974,
  [SMALL_STATE(49)] = 985,
  [SMALL_STATE(50)] = 996,
  [SMALL_STATE(51)] = 1007,
  [SMALL_STATE(52)] = 1018,
  [SMALL_STATE(53)] = 1029,
  [SMALL_STATE(54)] = 1040,
  [SMALL_STATE(55)] = 1059,
  [SMALL_STATE(56)] = 1070,
  [SMALL_STATE(57)] = 1081,
  [SMALL_STATE(58)] = 1092,
  [SMALL_STATE(59)] = 1103,
  [SMALL_STATE(60)] = 1122,
  [SMALL_STATE(61)] = 1141,
  [SMALL_STATE(62)] = 1152,
  [SMALL_STATE(63)] = 1163,
  [SMALL_STATE(64)] = 1174,
  [SMALL_STATE(65)] = 1193,
  [SMALL_STATE(66)] = 1209,
  [SMALL_STATE(67)] = 1225,
  [SMALL_STATE(68)] = 1241,
  [SMALL_STATE(69)] = 1254,
  [SMALL_STATE(70)] = 1267,
  [SMALL_STATE(71)] = 1278,
  [SMALL_STATE(72)] = 1291,
  [SMALL_STATE(73)] = 1304,
  [SMALL_STATE(74)] = 1315,
  [SMALL_STATE(75)] = 1328,
  [SMALL_STATE(76)] = 1339,
  [SMALL_STATE(77)] = 1349,
  [SMALL_STATE(78)] = 1359,
  [SMALL_STATE(79)] = 1365,
  [SMALL_STATE(80)] = 1375,
  [SMALL_STATE(81)] = 1385,
  [SMALL_STATE(82)] = 1395,
  [SMALL_STATE(83)] = 1405,
  [SMALL_STATE(84)] = 1412,
  [SMALL_STATE(85)] = 1419,
  [SMALL_STATE(86)] = 1426,
  [SMALL_STATE(87)] = 1433,
  [SMALL_STATE(88)] = 1440,
  [SMALL_STATE(89)] = 1445,
  [SMALL_STATE(90)] = 1452,
  [SMALL_STATE(91)] = 1459,
  [SMALL_STATE(92)] = 1466,
  [SMALL_STATE(93)] = 1471,
  [SMALL_STATE(94)] = 1478,
  [SMALL_STATE(95)] = 1483,
  [SMALL_STATE(96)] = 1490,
  [SMALL_STATE(97)] = 1497,
  [SMALL_STATE(98)] = 1504,
  [SMALL_STATE(99)] = 1511,
  [SMALL_STATE(100)] = 1518,
  [SMALL_STATE(101)] = 1525,
  [SMALL_STATE(102)] = 1532,
  [SMALL_STATE(103)] = 1539,
  [SMALL_STATE(104)] = 1546,
  [SMALL_STATE(105)] = 1551,
  [SMALL_STATE(106)] = 1558,
  [SMALL_STATE(107)] = 1565,
  [SMALL_STATE(108)] = 1572,
  [SMALL_STATE(109)] = 1579,
  [SMALL_STATE(110)] = 1586,
  [SMALL_STATE(111)] = 1593,
  [SMALL_STATE(112)] = 1600,
  [SMALL_STATE(113)] = 1607,
  [SMALL_STATE(114)] = 1614,
  [SMALL_STATE(115)] = 1619,
  [SMALL_STATE(116)] = 1626,
  [SMALL_STATE(117)] = 1633,
  [SMALL_STATE(118)] = 1640,
  [SMALL_STATE(119)] = 1647,
  [SMALL_STATE(120)] = 1652,
  [SMALL_STATE(121)] = 1659,
  [SMALL_STATE(122)] = 1666,
  [SMALL_STATE(123)] = 1673,
  [SMALL_STATE(124)] = 1680,
  [SMALL_STATE(125)] = 1687,
  [SMALL_STATE(126)] = 1694,
  [SMALL_STATE(127)] = 1699,
  [SMALL_STATE(128)] = 1706,
  [SMALL_STATE(129)] = 1713,
  [SMALL_STATE(130)] = 1720,
  [SMALL_STATE(131)] = 1727,
  [SMALL_STATE(132)] = 1734,
  [SMALL_STATE(133)] = 1741,
  [SMALL_STATE(134)] = 1748,
  [SMALL_STATE(135)] = 1752,
  [SMALL_STATE(136)] = 1756,
  [SMALL_STATE(137)] = 1760,
  [SMALL_STATE(138)] = 1764,
  [SMALL_STATE(139)] = 1768,
  [SMALL_STATE(140)] = 1772,
  [SMALL_STATE(141)] = 1776,
  [SMALL_STATE(142)] = 1780,
  [SMALL_STATE(143)] = 1784,
  [SMALL_STATE(144)] = 1788,
  [SMALL_STATE(145)] = 1792,
  [SMALL_STATE(146)] = 1796,
  [SMALL_STATE(147)] = 1800,
  [SMALL_STATE(148)] = 1804,
  [SMALL_STATE(149)] = 1808,
  [SMALL_STATE(150)] = 1812,
  [SMALL_STATE(151)] = 1816,
  [SMALL_STATE(152)] = 1820,
  [SMALL_STATE(153)] = 1824,
  [SMALL_STATE(154)] = 1828,
  [SMALL_STATE(155)] = 1832,
  [SMALL_STATE(156)] = 1836,
  [SMALL_STATE(157)] = 1840,
  [SMALL_STATE(158)] = 1844,
  [SMALL_STATE(159)] = 1848,
  [SMALL_STATE(160)] = 1852,
  [SMALL_STATE(161)] = 1856,
  [SMALL_STATE(162)] = 1860,
  [SMALL_STATE(163)] = 1864,
  [SMALL_STATE(164)] = 1868,
  [SMALL_STATE(165)] = 1872,
  [SMALL_STATE(166)] = 1876,
  [SMALL_STATE(167)] = 1880,
  [SMALL_STATE(168)] = 1884,
  [SMALL_STATE(169)] = 1888,
  [SMALL_STATE(170)] = 1892,
  [SMALL_STATE(171)] = 1896,
  [SMALL_STATE(172)] = 1900,
  [SMALL_STATE(173)] = 1904,
  [SMALL_STATE(174)] = 1908,
  [SMALL_STATE(175)] = 1912,
  [SMALL_STATE(176)] = 1916,
  [SMALL_STATE(177)] = 1920,
  [SMALL_STATE(178)] = 1924,
  [SMALL_STATE(179)] = 1928,
  [SMALL_STATE(180)] = 1932,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_else_clause, 2, 0, 0), SHIFT(67),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_else_clause, 1, 0, 0), SHIFT(67),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 7, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 7, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 5, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 5, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 5, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 5, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_block, 4, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_block, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_close, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_close, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_close, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_close, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_block, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_block, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_close, 4, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_close, 4, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 4, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 4, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_block, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_block, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_close, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_close, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_block, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_block, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 4, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_block, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_block, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 6, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 6, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_close, 5, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_close, 5, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_close, 5, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_close, 5, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_close, 6, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_close, 6, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_block, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_block, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_close, 5, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_close, 5, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_close, 6, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_close, 6, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_close, 6, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_close, 6, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_block, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_block, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_close, 6, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_close, 6, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_close, 5, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_close, 5, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_block, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_block, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_block, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_block, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_open, 8, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_open, 8, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_open, 13, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_open, 13, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_open, 11, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_open, 11, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_open, 7, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_open, 7, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_open, 7, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_open, 7, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_open, 12, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_open, 12, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_open, 6, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_open, 6, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_open, 5, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_open, 5, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_open, 4, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_open, 4, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_open, 10, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_open, 10, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_open, 8, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_open, 8, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_open, 5, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_open, 5, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_open, 4, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_open, 4, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(164),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsecure_open, 6, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsecure_open, 6, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_open, 6, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_open, 6, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_open, 6, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_open, 6, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [303] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(152),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_args, 1, 0, 0),
  [324] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_include_args, 1, 0, 0), SHIFT(96),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_include_args_repeat1, 2, 0, 0),
  [333] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_include_args_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(165),
  [350] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_index, 4, 0, 0),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_index, 3, 0, 0),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(178),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(166),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(176),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [386] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_index, 2, 0, 0),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(167),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(172),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(157),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(170),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(169),
  [416] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_arg, 5, 0, 0),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [420] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(174),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(177),
  [428] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_arg, 4, 0, 0),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [432] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [436] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [438] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [440] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [442] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [444] = {.entry = {.count = 1, .reusable = true}}, SHIFT(163),
  [446] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [448] = {.entry = {.count = 1, .reusable = true}}, SHIFT(168),
  [450] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_arg, 3, 0, 0),
  [452] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [454] = {.entry = {.count = 1, .reusable = true}}, SHIFT(171),
  [456] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [458] = {.entry = {.count = 1, .reusable = true}}, SHIFT(173),
  [460] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [462] = {.entry = {.count = 1, .reusable = true}}, SHIFT(180),
  [464] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [466] = {.entry = {.count = 1, .reusable = true}}, SHIFT(162),
  [468] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [470] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [472] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [474] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [476] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [478] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [480] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [482] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [484] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [486] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [488] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [490] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [492] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [494] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [496] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [498] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [500] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [502] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [504] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [506] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [508] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [510] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [512] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [514] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [516] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [518] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [520] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [522] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [524] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [526] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [528] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [530] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [532] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [534] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_natsuzora(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
